import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const AccountShiper = sequelize.define(
    "account-shiper",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        as_nbr:{
            type: Sequelize.STRING,
            unique: true,
        },
        as_bill: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
        as_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
    as_type: Sequelize.STRING, 
    as_so_nbr: Sequelize.STRING, 
    as_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_effdate: Sequelize.DATEONLY, 
    as_date: Sequelize.DATEONLY, 
    as_cr_terms: Sequelize.STRING, 
    as_po: Sequelize.STRING, 
    as_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_disc_date: Sequelize.DATEONLY, 
    as_due_date: Sequelize.DATEONLY, 
    as_expt_date: Sequelize.DATEONLY, 
    as_acct: Sequelize.STRING, 
    as_cc: Sequelize.STRING, 
    as_sales_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_xslspsn1: Sequelize.STRING, 
    as_xslspsn2: Sequelize.STRING, 
    as_paid_date: Sequelize.DATEONLY, 
    as_batch: Sequelize.STRING, 
    as_disc_acct: Sequelize.STRING, 
    as_disc_cc: Sequelize.STRING, 
    as_ship: Sequelize.STRING, 
    as_open: {type: Sequelize.BOOLEAN, defaultValue : true  }, 
    as_contested: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_check: Sequelize.STRING, 
    as_cmtindx: Sequelize.INTEGER, 
    as_user1: Sequelize.STRING, 
    as_user2: Sequelize.STRING, 
    as_curr: Sequelize.STRING, 
    as_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_vas_acct: Sequelize.STRING, 
    as_vas_cc: Sequelize.STRING, 
    as_bank: Sequelize.STRING, 
    as_mrgn_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_entity: Sequelize.STRING, 
    as_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as__chr01: Sequelize.STRING, 
    as__chr02: Sequelize.STRING, 
    as__chr03: Sequelize.STRING, 
    as__chr04: Sequelize.STRING, 
    as__chr05: Sequelize.STRING, 
    as__dte01: Sequelize.DATEONLY, 
    as__dte02: Sequelize.DATEONLY, 
    as__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as__log01: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_draft: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_ldue_date: Sequelize.DATEONLY, 
    as_print: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_inv_cr: Sequelize.STRING, 
    as_fr_terms: Sequelize.STRING, 
    as_slspsn: Sequelize.STRING, 
    as_tax_date: Sequelize.DATEONLY, 
    as_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_tax_env: Sequelize.STRING, 
    as__qad01: Sequelize.STRING, 
    as__qad02: Sequelize.STRING, 
    as__qad03: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_drft_sel: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_coll_mthd: Sequelize.STRING, 
    as_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_disc_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_base_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_fsm_type: Sequelize.STRING, 
    as_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_dy_code: Sequelize.STRING, 
    as_dun_level: Sequelize.INTEGER, 
    as_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_ex_ratetype: Sequelize.STRING, 
    as_base_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_base_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_base_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_exru_seq: Sequelize.INTEGER, 
    as_dd_curr: Sequelize.STRING, 
    as_dd_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_dd_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    as_dd_exru_seq: Sequelize.INTEGER, 
    as_app_owner: Sequelize.STRING, 
    as_sub: Sequelize.STRING, 
    as_disc_sub: Sequelize.STRING, 
    as_vas_sub: Sequelize.STRING, 
    as_prepayment: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_shipfrom: Sequelize.STRING, 
    as_customer_bank: Sequelize.STRING, 
    as_draft_disc_date: Sequelize.DATEONLY, 
    as_recon_date: Sequelize.DATEONLY, 
    as_status: Sequelize.STRING, 
    as_customer_initiated: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    as_draft_submit_date: Sequelize.DATEONLY, 
    as_pay_method: Sequelize.STRING, 
    as_void_date: Sequelize.DATEONLY, 
    as_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
    oid_as_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
    ...base,
    },
    {
        tableName: "as_mstr",
    }
)
export default AccountShiper
