import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const AccountReceivable = sequelize.define(
    "account-receivable",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        ar_nbr: Sequelize.STRING,
           
        ar_bill: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
        ar_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
    ar_type: Sequelize.STRING, 
    ar_so_nbr: Sequelize.STRING, 
    ar_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_effdate: Sequelize.DATEONLY, 
    ar_date: Sequelize.DATEONLY, 
    ar_cr_terms: Sequelize.STRING, 
    ar_po: Sequelize.STRING, 
    ar_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_disc_date: Sequelize.DATEONLY, 
    ar_due_date: Sequelize.DATEONLY, 
    ar_expt_date: Sequelize.DATEONLY, 
    ar_acct: Sequelize.STRING, 
    ar_cc: Sequelize.STRING, 
    ar_sales_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_xslspsn1: Sequelize.STRING, 
    ar_xslspsn2: Sequelize.STRING, 
    ar_paid_date: Sequelize.DATEONLY, 
    ar_batch: Sequelize.STRING, 
    ar_disc_acct: Sequelize.STRING, 
    ar_disc_cc: Sequelize.STRING, 
    ar_ship: Sequelize.STRING, 
    ar_open: {type: Sequelize.BOOLEAN, defaultValue : true  }, 
    ar_contested: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_check: Sequelize.STRING, 
    ar_cmtindx: Sequelize.INTEGER, 
    ar_user1: Sequelize.STRING, 
    ar_user2: Sequelize.STRING, 
    ar_curr: Sequelize.STRING, 
    ar_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_var_acct: Sequelize.STRING, 
    ar_var_cc: Sequelize.STRING, 
    ar_bank: Sequelize.STRING, 
    ar_mrgn_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_entity: Sequelize.STRING, 
    ar_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar__chr01: Sequelize.STRING, 
    ar__chr02: Sequelize.STRING, 
    ar__chr03: Sequelize.STRING, 
    ar__chr04: Sequelize.STRING, 
    ar__chr05: Sequelize.STRING, 
    ar__dte01: Sequelize.DATEONLY, 
    ar__dte02: Sequelize.DATEONLY, 
    ar__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar__log01: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_draft: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_ldue_date: Sequelize.DATEONLY, 
    ar_print: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_inv_cr: Sequelize.STRING, 
    ar_fr_terms: Sequelize.STRING, 
    ar_slspsn: Sequelize.STRING, 
    ar_tax_date: Sequelize.DATEONLY, 
    ar_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_tax_env: Sequelize.STRING, 
    ar__qad01: Sequelize.STRING, 
    ar__qad02: Sequelize.STRING, 
    ar__qad03: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_drft_sel: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_coll_mthd: Sequelize.STRING, 
    ar_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_disc_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_base_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_fsm_type: Sequelize.STRING, 
    ar_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_dy_code: Sequelize.STRING, 
    ar_dun_level: Sequelize.INTEGER, 
    ar_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_ex_ratetype: Sequelize.STRING, 
    ar_base_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_base_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_base_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_exru_seq: Sequelize.INTEGER, 
    ar_dd_curr: Sequelize.STRING, 
    ar_dd_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_dd_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ar_dd_exru_seq: Sequelize.INTEGER, 
    ar_app_owner: Sequelize.STRING, 
    ar_sub: Sequelize.STRING, 
    ar_disc_sub: Sequelize.STRING, 
    ar_var_sub: Sequelize.STRING, 
    ar_prepayment: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_shipfrom: Sequelize.STRING, 
    ar_customer_bank: Sequelize.STRING, 
    ar_draft_disc_date: Sequelize.DATEONLY, 
    ar_recon_date: Sequelize.DATEONLY, 
    ar_status: Sequelize.STRING, 
    ar_customer_initiated: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ar_draft_submit_date: Sequelize.DATEONLY, 
    ar_pay_method: Sequelize.STRING, 
    ar_void_date: Sequelize.DATEONLY, 
    ar_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
    oid_ar_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
    ...base,
    },
    {
        tableName: "ar_mstr",
    }
)
export default AccountReceivable
