import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const dailySalesAccessoire = sequelize.define(
    "dailysalesAccessoire",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        dsd__nbr: {
            type: Sequelize.STRING,
            references: {
                model: "so_mstr",
                key: "so_nbr",
            },
        },
        dsd__line: Sequelize.INTEGER,
        dsd__part: {
            type: Sequelize.STRING,
            references:{
                model: "acs_mstr",
                key: "acs_part",
            },

        },

        dsd__tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
    dsd__due_date: Sequelize.DATEONLY,
    dsd__per_date: Sequelize.DATEONLY,
    dsd__req_date: Sequelize.DATEONLY,
    dsd__qty_ord:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__qty_ship:   {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__qty_inv:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__loc: Sequelize.STRING,
    dsd__type: Sequelize.STRING,
    dsd__price: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__sales_price: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__qty_chg:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    dsd__bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__acct: Sequelize.STRING,
    dsd__abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__serial: Sequelize.STRING,
    dsd__desc: Sequelize.STRING,
    dsd__um: Sequelize.STRING,
    dsd__cc: Sequelize.STRING,
    dsd__comment: Sequelize.STRING,
    dsd__lot: Sequelize.STRING,
    dsd__um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__fa_nbr: Sequelize.STRING,
    dsd__disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__project: Sequelize.STRING,
    dsd__cmtindx: Sequelize.INTEGER,
    dsd__custpart: Sequelize.STRING,
    dsd___qad01: Sequelize.INTEGER,
    dsd__status: Sequelize.STRING,
    dsd__xslspsn: Sequelize.STRING,
    dsd__xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__dsc_acct: Sequelize.STRING,
    dsd__dsc_cc: Sequelize.STRING,
    dsd__list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__user1: Sequelize.STRING,
    dsd__user2: Sequelize.STRING,
    dsd__sob_rev: Sequelize.DATEONLY,
    dsd__sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__expire: Sequelize.DATEONLY,
    dsd___qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__taxc: Sequelize.STRING,
    dsd__inv_nbr: Sequelize.STRING,
    dsd__partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__site: Sequelize.STRING,
    dsd__prodline: Sequelize.STRING,
    dsd__tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd___chr01: Sequelize.STRING,
    dsd___chr02: Sequelize.STRING,
    dsd___chr03: Sequelize.STRING,
    dsd___chr04: Sequelize.STRING,
    dsd___chr05: Sequelize.STRING,
    dsd___chr06: Sequelize.STRING,
    dsd___chr07: Sequelize.STRING,
    dsd___chr08: Sequelize.STRING,
    dsd___chr09: Sequelize.STRING,
    dsd___chr10: Sequelize.STRING,
    dsd___dte01: Sequelize.DATEONLY,
    dsd___dte02: Sequelize.DATEONLY,
    dsd___dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd___dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd___log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__curr_rlse_id: Sequelize.STRING,
    dsd__sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__contr_id: Sequelize.STRING,
    dsd__pickdate: Sequelize.DATEONLY,
    dsd__confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__cum_date: Sequelize.DATEONLY,
    dsd__for: Sequelize.STRING,
    dsd__ref: Sequelize.STRING,
    dsd__qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__rma_type: Sequelize.STRING,
    dsd__owner: Sequelize.STRING,
    dsd__calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__slspsn: Sequelize.STRING,
    dsd__comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__pkg_code: Sequelize.STRING,
    dsd__translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__fsm_type: Sequelize.STRING,
    dsd__conrep: Sequelize.STRING,
    dsd__sch_data: Sequelize.STRING,
    dsd__sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__rlse_nbr: Sequelize.INTEGER,
    dsd__start_eff: Sequelize.DATEONLY,
    dsd__end_eff: Sequelize.DATEONLY,
    dsd__dock: Sequelize.STRING,
    dsd__pr_list: Sequelize.STRING,
    dsd__translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__out_po: Sequelize.STRING,
    dsd__raw_days: Sequelize.INTEGER,
    dsd__fab_days: Sequelize.INTEGER,
    dsd__tax_usage: Sequelize.STRING,
    dsd__rbkt_days: Sequelize.INTEGER,
    dsd__rbkt_weeks: Sequelize.INTEGER,
    dsd__rbkt_mths: Sequelize.INTEGER,
    dsd__sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__pastdue: Sequelize.STRING,
    dsd__fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__fr_wt_um: Sequelize.STRING,
    dsd__fr_class: Sequelize.STRING,
    dsd__fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__ship: Sequelize.STRING,
    dsd__sa_nbr: Sequelize.STRING,
    dsd__enduser: Sequelize.STRING,
    dsd__isb_loc: Sequelize.STRING,
    dsd__upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__isb_ref: Sequelize.INTEGER,
    dsd__auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__drp_ref: Sequelize.STRING,
    dsd__tax_env: Sequelize.STRING,
    dsd__crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__fr_list: Sequelize.STRING,
    dsd__pricing_dt: Sequelize.DATEONLY,
    dsd__act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__ca_line: Sequelize.INTEGER,
    dsd__qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__ca_nbr: Sequelize.STRING,
    dsd__qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__to_loc: Sequelize.STRING,
    dsd__to_site: Sequelize.STRING,
    dsd__to_ref: Sequelize.STRING,
    dsd__ln_ref: Sequelize.STRING,
    dsd__qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__sad_line: Sequelize.INTEGER,
    dsd__warr_start: Sequelize.DATEONLY,
    dsd__mod_userid: Sequelize.STRING,
    dsd__mod_date: Sequelize.DATEONLY,
    dsd__sv_code: Sequelize.STRING,
    dsd__alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__for_serial: Sequelize.STRING,
    dsd__override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd___qadc01: Sequelize.STRING,
    dsd___qadc02: Sequelize.STRING,
    dsd___qadc03: Sequelize.STRING,
    dsd___qadc04: Sequelize.STRING,
    dsd___qadt01: Sequelize.DATEONLY,
    dsd___qadt02: Sequelize.DATEONLY,
    dsd___qadt03: Sequelize.DATEONLY,
    dsd___qadt04: Sequelize.DATEONLY,
    dsd___qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd___qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd___qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd___qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd___qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd___qadl03: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd___qadi01: Sequelize.INTEGER,
    dsd___qadi02: Sequelize.INTEGER,
    dsd__bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__btb_type: Sequelize.STRING,
    dsd__btb_po: Sequelize.STRING,
    dsd__btb_pod_line: Sequelize.INTEGER,
    dsd__btb_vend: Sequelize.STRING,
    dsd__exp_del: Sequelize.DATEONLY,
    dsd__dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__cfg_type: Sequelize.STRING,
    dsd__div: Sequelize.STRING,
    dsd__pl_priority: Sequelize.INTEGER,
    dsd__prig1: Sequelize.STRING,
    dsd__prig2: Sequelize.STRING,
    dsd___qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__sub: Sequelize.STRING,
    dsd__dsc_sub: Sequelize.STRING,
    dsd__dsc_project: Sequelize.STRING,
    dsd__qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
    dsd__cum_time: Sequelize.INTEGER,
    dsd__ship_part: Sequelize.STRING,
    dsd__promise_date: Sequelize.DATEONLY,
    dsd__charge_type: Sequelize.STRING,
    dsd__order_category: Sequelize.STRING,
    dsd__modelyr: Sequelize.STRING,
    dsd__custref: Sequelize.STRING,
    dsd__consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__max_aging_days: Sequelize.INTEGER,
    dsd__consign_loc: Sequelize.STRING,
    dsd__intrans_loc: Sequelize.STRING,
    dsd__auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
    dsd__req_time: Sequelize.STRING,


    dsd__domain: {
        type: Sequelize.STRING,
        defaultValue: 'zitouni'
    },
    oid_dsd__det: {type: Sequelize.DECIMAL, defaultValue : 0  },
    ...base,
        },
        {
            tableName: "dsd__det",
        }
)
export default dailySalesAccessoire
