import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const Glasses = sequelize.define(
    "glasses",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        gls_part: {
            type: Sequelize.STRING,
            primaryKey: true,
            unique: true
        },
        gls_desc1: Sequelize.STRING,
        gls_desc2: Sequelize.STRING,
        gls_um: Sequelize.STRING,
        gls_draw: Sequelize.STRING,
        gls_prod_line: {
            type: Sequelize.STRING,
            references:{
                model: "pl_mstr",
                key: "pl_prod_line",
            },

        },
        gls_group: Sequelize.STRING,
        gls_part_type: Sequelize.STRING,
        gls_status: Sequelize.STRING,
        gls_abc: Sequelize.STRING,
        gls_iss_pol: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_phantom: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_loc:{
            type: Sequelize.STRING,
            references:{
                model: "loc_mstr",
                key: "loc_loc",
            },

        },
        gls_abc_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_avg_int: Sequelize.INTEGER,
        gls_cyc_int: Sequelize.INTEGER,
        gls_ms: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_plan_ord: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_ord_pol: Sequelize.STRING,
        gls_ord_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_ord_per: Sequelize.INTEGER,
        gls_sfty_stk: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_sfty_time: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_rop: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_buyer: Sequelize.STRING,
        gls_vend: Sequelize.STRING,
        gls_pm_code: Sequelize.STRING,
        gls_mfg_lead: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_pur_lead: Sequelize.INTEGER,
        gls_insp_rqd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_insp_lead: Sequelize.INTEGER,
        gls_cum_lead: Sequelize.INTEGER,
        gls_ord_min: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_ord_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_yield_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_setup: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_setup_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_run_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_run: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_pur_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xmtl_tl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xlbr_tl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xbdn_tl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xsub_tl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xmtl_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xlbr_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xbdn_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xsub_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xtot_cur: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_cur_date: Sequelize.DATEONLY,
        gls_xmtl_stdtl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xlbr_stdtl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xbdn_stdtl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xsub_stdtl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xtot_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_std_date: Sequelize.DATEONLY,
        gls_ll_code: Sequelize.INTEGER,
        gls_abc_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_routing: Sequelize.STRING,
        gls_lot_ser: Sequelize.STRING,
        gls_timefence: Sequelize.INTEGER,
        gls_xmtl_stdll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xlbr_stdll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xbdn_stdll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xsub_stdll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_rev: Sequelize.STRING,
        gls_last_eco: Sequelize.DATEONLY,
        gls_qc_lead: Sequelize.INTEGER,
        gls_auto_lot: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_assay: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_batch: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_user3: Sequelize.STRING,
        gls_user2: Sequelize.STRING,
        gls_user1: Sequelize.STRING,
        gls_net_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_net_wt_um: Sequelize.STRING,
        gls_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_size_um: Sequelize.STRING,
        gls_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_taxc: Sequelize.STRING,
        gls_rollup: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_xovh_ll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xovh_tl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xovh_stdll: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_xovh_stdtl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_site: Sequelize.STRING,
        gls_shelflife: Sequelize.INTEGER,
        gls_critical: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_sngl_lot: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_upc: Sequelize.STRING,
        gls_hazard: Sequelize.STRING,
        
        gls_added: Sequelize.DATEONLY,

        gls_cyl_beging: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_cyl_end: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_sph_beging: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_sph_end: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_add_beging: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_add_end: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_base: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_prisme: {type: Sequelize.DECIMAL, defaultValue : 0  },

        gls_length: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_height: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_width: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_dim_um: Sequelize.STRING,
        gls_pkg_code: Sequelize.STRING,
        gls_network: Sequelize.STRING,
        gls_fr_class: Sequelize.STRING,
        gls_spec_hdlg: Sequelize.STRING,
        gls_bom_code: Sequelize.STRING,
        gls_loc_type: Sequelize.STRING,
        gls_transtype: Sequelize.STRING,
        gls_warr_cd: Sequelize.STRING,
        gls_pvm_days: Sequelize.INTEGER,
        gls_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_mttr: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_mtbf: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_svc_type: Sequelize.STRING,
        gls_svc_group: Sequelize.STRING,
        gls_ven_warr: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_fru: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_mfg_mttr: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_mfg_mtbf: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_sttr: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_origin: Sequelize.STRING,
        gls_tariff: Sequelize.STRING,
        gls_sys_type: Sequelize.STRING,
        gls_inst_call: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_cover: Sequelize.STRING,
        gls_unit_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_article: Sequelize.STRING,
        gls_ll_drp: Sequelize.INTEGER,
        gls_po_site: Sequelize.STRING,
        gls_ship_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_ship_wt_um: Sequelize.STRING,
        gls_userid: Sequelize.STRING,
        gls_mod_date: Sequelize.DATEONLY,
        gls_comm_code: Sequelize.STRING,
        gls_dea: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_formula: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_obs_date: Sequelize.DATEONLY,
        gls_pvm_bom: Sequelize.STRING,
        gls_pvm_route: Sequelize.STRING,
        gls_pvm_um: Sequelize.STRING,
        gls_rp_bom: Sequelize.STRING,
        gls_rp_route: Sequelize.STRING,
        gls_rp_vendor: Sequelize.STRING,
        gls_rctpo_status: Sequelize.STRING,
        gls_rollup_id: Sequelize.STRING,
        gls_spec_grav: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_joint_type: Sequelize.STRING,
        gls_mfg_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_pur_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_drp_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_pou_code: Sequelize.STRING,
        gls_wks_avg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_wks_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_wks_min: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_pick_logic: Sequelize.INTEGER,
        gls_fiscal_class: Sequelize.STRING,
        gls_dsgn_grp: Sequelize.STRING,
        gls_drwg_loc: Sequelize.STRING,
        gls_ecn_rev: Sequelize.STRING,
        gls_drwg_size: Sequelize.STRING,
        gls_model: Sequelize.STRING,
        gls_repairable: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_rctwo_status: Sequelize.STRING,
        gls_rctpo_active: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_lot_grp: Sequelize.STRING,
        gls_rctwo_active: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_break_cat: Sequelize.STRING,
        gls_fsc_code: Sequelize.STRING,
        gls_trace_active: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_trace_detail: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_pm_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_ins_call_type: Sequelize.STRING,
        gls_ins_bom: Sequelize.STRING,
        gls_ins_route: Sequelize.STRING,
        gls_promo: Sequelize.STRING,
        gls_meter_interval: {type: Sequelize.DECIMAL, defaultValue : 0  },
        gls_meter_um: Sequelize.STRING,
        gls_wh: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_btb_type: Sequelize.STRING,
        gls_cfg_type: Sequelize.STRING,
        gls_app_owner: Sequelize.STRING,
        gls_op_yield: Sequelize.STRING,
        gls_run_seq1: Sequelize.STRING,
        gls_run_seq2: Sequelize.STRING,
        gls_atp_enforcement: Sequelize.STRING,
        gls_atp_family: {type: Sequelize.BOOLEAN, defaultValue : false  },
        gls_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        oid_gls_mstr: Sequelize.STRING,
        ...base,
    },
    {
        tableName: "gls_mstr",
    }
)
export default Glasses
