import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const InventoryTransaction = sequelize.define(
    "InventoryTransaction",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        tr_part: Sequelize.STRING,
            
        tr_date: Sequelize.DATEONLY,
        tr_per_date: Sequelize.DATEONLY,
        tr_lot: Sequelize.STRING,
        tr_type: Sequelize.STRING,
        tr_loc: Sequelize.STRING,
        tr_loc_begin: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_begin_qoh: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_qty_req: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_qty_short: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_um: Sequelize.STRING,
        tr_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_last_date: Sequelize.DATEONLY,
        tr_nbr: Sequelize.STRING,
        tr_so_job: Sequelize.STRING,
        tr_ship_type: Sequelize.STRING,
        tr_addr: Sequelize.STRING,
        tr_rmks: Sequelize.STRING,
        tr_xdr_acct: Sequelize.STRING,
        tr_xcr_acct: Sequelize.STRING,
        tr_mtl_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_lbr_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_bdn_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_trnbr: Sequelize.INTEGER,
        tr_gl_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_xdr_cc: Sequelize.STRING,
        tr_xcr_cc: Sequelize.STRING,
        tr_sub_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_gl_date: Sequelize.DATEONLY,
        tr_qty_loc: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_userid: Sequelize.STRING,
        tr_serial: Sequelize.STRING,
        tr_effdate: Sequelize.DATEONLY,
        tr_prod_line: Sequelize.STRING,
        tr_xslspsn1: Sequelize.STRING,
        tr_xslspsn2: Sequelize.STRING,
        tr_xcr_proj: Sequelize.STRING,
        tr_xdr_proj: Sequelize.STRING,
        tr_line: Sequelize.INTEGER,
        tr_user1: Sequelize.STRING,
        tr_user2: Sequelize.STRING,
        tr_curr: Sequelize.STRING,
        tr_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_rev: Sequelize.STRING,
        tr_time: Sequelize.INTEGER,
        tr_ovh_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_site: Sequelize.STRING,
        tr_status: Sequelize.STRING,
        tr_grade: Sequelize.STRING,
        tr_expire: Sequelize.DATEONLY,
        tr_assay: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_xgl_ref: Sequelize.STRING,
        tr__chr01: Sequelize.STRING,
        tr__chr02: Sequelize.STRING,
        tr__chr03: Sequelize.STRING,
        tr__chr04: Sequelize.STRING,
        tr__chr05: Sequelize.STRING,
        tr__chr06: Sequelize.STRING,
        tr__chr07: Sequelize.STRING,
        tr__chr08: Sequelize.STRING,
        tr__chr09: Sequelize.STRING,
        tr__chr10: Sequelize.STRING,
        tr__chr11: Sequelize.STRING,
        tr__chr12: Sequelize.STRING,
        tr__chr13: Sequelize.STRING,
        tr__chr14: Sequelize.STRING,
        tr__chr15: Sequelize.STRING,
        tr__dte01: Sequelize.DATEONLY,
        tr__dte02: Sequelize.DATEONLY,
        tr__dte03: Sequelize.DATEONLY,
        tr__dte04: Sequelize.DATEONLY,
        tr__dte05: Sequelize.DATEONLY,
        tr__dec01: {type: Sequelize.DECIMAL  },
        tr__dec02: {type: Sequelize.DECIMAL  },
        tr__dec03: {type: Sequelize.DECIMAL  },
        tr__dec04: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr__dec05: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        tr__log02: {type: Sequelize.BOOLEAN, defaultValue : false  },
        tr_ref: Sequelize.STRING,
        tr_msg: Sequelize.INTEGER,
        tr_program: Sequelize.STRING,
        tr_ord_rev: Sequelize.INTEGER,
        tr_ref_site: Sequelize.STRING,
        tr_ref_loc: Sequelize.STRING,
        tr_for: Sequelize.STRING,
        tr_rsn_code: Sequelize.STRING,
        tr_daycode: Sequelize.STRING,
        tr_vend_date: Sequelize.DATEONLY,
        tr_vend_lot: Sequelize.STRING,
        tr_slspsn: Sequelize.STRING,
        tr_fsm_type: Sequelize.STRING,
        tr_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
        tr_auto_install: {type: Sequelize.BOOLEAN, defaultValue : false  },
        tr_ca_int_type: Sequelize.STRING,
        tr_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_batch: Sequelize.STRING,
        tr_fcg_code: Sequelize.STRING,
        tr_fsc_code: Sequelize.STRING,
        tr_sa_nbr: Sequelize.STRING,
        tr_sv_code: Sequelize.STRING,
        tr_eng_area: Sequelize.STRING,
        tr_sys_prod: Sequelize.STRING,
        tr_svc_type: Sequelize.STRING,
        tr_ca_opn_date: Sequelize.STRING,
        tr_cprice: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_eng_code: Sequelize.STRING,
        tr_wod_op: Sequelize.INTEGER,
        tr_enduser: Sequelize.STRING,
        tr_ship_inv_mov: Sequelize.STRING,
        tr_ship_date: Sequelize.DATEONLY,
        tr_ship_id: Sequelize.STRING,
        tr_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
        tr_ex_ratetype: Sequelize.STRING,
        tr_exru_seq: Sequelize.INTEGER,
        tr_promise_date: Sequelize.DATEONLY,
        tr_fldchg_cmtindx: Sequelize.INTEGER,
        tr_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        ...base,
    },
    {
        tableName: "tr_hist",
    }
)

export default InventoryTransaction
