import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const InvoiceOrderTempDetail = sequelize.define(
    "InvoiceOrderTempDetail",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },       
        itdh_inv_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "ith_hist",
                key: "ith_inv_nbr",
            },
        },
        itdh_line: Sequelize.INTEGER,
        itdh_part: {
            type: Sequelize.STRING,
            references:{
                model: "pt_mstr",
                key: "pt_part",
            },

        },

        itdh_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
itdh_due_date: Sequelize.DATEONLY,
itdh_per_date: Sequelize.DATEONLY,
itdh_req_date: Sequelize.DATEONLY,
itdh_qty_ord:  {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_ship: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_inv: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_loc: Sequelize.STRING,
itdh_type: Sequelize.STRING,
itdh_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_acct: Sequelize.STRING,
itdh_abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_serial: Sequelize.STRING,
itdh_desc: Sequelize.STRING,
itdh_um: Sequelize.STRING,
itdh_cc: Sequelize.STRING,
itdh_comment: Sequelize.STRING,
itdh_lot: Sequelize.STRING,
itdh_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_fa_nbr: Sequelize.STRING,
itdh_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_project: Sequelize.STRING,
itdh_cmtindx: Sequelize.INTEGER,
itdh_custpart: Sequelize.STRING,
itdh__qad01: Sequelize.INTEGER,
itdh_status: Sequelize.STRING,
itdh_xslspsn: Sequelize.STRING,
itdh_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_dsc_acct: Sequelize.STRING,
itdh_dsc_cc: Sequelize.STRING,
itdh_list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_user1: Sequelize.STRING,
itdh_user2: Sequelize.STRING,
itdh_sob_rev: Sequelize.DATEONLY,
itdh_sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_expire: Sequelize.DATEONLY,
itdh__qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_taxc: Sequelize.STRING,
itdh_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_site: Sequelize.STRING,
itdh_prodline: Sequelize.STRING,
itdh_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh__chr01: Sequelize.STRING,
itdh__chr02: Sequelize.STRING,
itdh__chr03: Sequelize.STRING,
itdh__chr04: Sequelize.STRING,
itdh__chr05: Sequelize.STRING,
itdh__chr06: Sequelize.STRING,
itdh__chr07: Sequelize.STRING,
itdh__chr08: Sequelize.STRING,
itdh__chr09: Sequelize.STRING,
itdh__chr10: Sequelize.STRING,
itdh__dte01: Sequelize.DATEONLY,
itdh__dte02: Sequelize.DATEONLY,
itdh__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_curr: Sequelize.STRING,
itdh_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_curr_rlse_id: Sequelize.STRING,
itdh_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_contr_id: Sequelize.STRING,
itdh_pickdate: Sequelize.DATEONLY,
itdh_confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_cum_date: Sequelize.DATEONLY,
itdh_for: Sequelize.STRING,
itdh_ref: Sequelize.INTEGER,
itdh_qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_rma_type: Sequelize.STRING,
itdh_owner: Sequelize.STRING,
itdh_calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_slspsn: Sequelize.STRING,
itdh_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_pkg_code: Sequelize.STRING,
itdh_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_fsm_type: Sequelize.STRING,
itdh_conrep: Sequelize.STRING,
itdh_sch_data: Sequelize.STRING,
itdh_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_rlse_nbr: Sequelize.INTEGER,
itdh_start_eff: Sequelize.DATEONLY,
itdh_end_eff: Sequelize.DATEONLY,
itdh_dock: Sequelize.STRING,
itdh_pr_list: Sequelize.STRING,
itdh_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_out_po: Sequelize.STRING,
itdh_raw_days: Sequelize.INTEGER,
itdh_fab_days: Sequelize.INTEGER,
itdh_tax_usage: Sequelize.STRING,
itdh_rbkt_days: Sequelize.INTEGER,
itdh_rbkt_weeks: Sequelize.INTEGER,
itdh_rbkt_mths: Sequelize.INTEGER,
itdh_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_pastdue: Sequelize.STRING,
itdh_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_fr_wt_um: Sequelize.STRING,
itdh_fr_class: Sequelize.STRING,
itdh_fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_ship: Sequelize.STRING,
itdh_sa_nbr: Sequelize.STRING,
itdh_enduser: Sequelize.STRING,
itdh_isb_loc: Sequelize.STRING,
itdh_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_isb_ref: Sequelize.INTEGER,
itdh_auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_drp_ref: Sequelize.STRING,
itdh_tax_env: Sequelize.STRING,
itdh_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_fr_list: Sequelize.STRING,
itdh_pricing_dt: Sequelize.DATEONLY,
itdh_act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_ca_line: Sequelize.INTEGER,
itdh_qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_ca_nbr: Sequelize.STRING,
itdh_qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_to_loc: Sequelize.STRING,
itdh_to_site: Sequelize.STRING,
itdh_to_ref: Sequelize.STRING,
itdh_ln_ref: Sequelize.STRING,
itdh_qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_sad_line: Sequelize.INTEGER,
itdh_warr_start: Sequelize.DATEONLY,
itdh_mod_userid: Sequelize.STRING,
itdh_mod_date: Sequelize.DATEONLY,
itdh_sv_code: Sequelize.STRING,
itdh_alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_for_serial: Sequelize.STRING,
itdh_override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh__qadc01: Sequelize.STRING,
itdh__qadc02: Sequelize.STRING,
itdh__qadc03: Sequelize.STRING,
itdh__qadc04: Sequelize.STRING,
itdh__qadt01: Sequelize.DATEONLY,
itdh__qadt02: Sequelize.DATEONLY,
itdh__qadt03: Sequelize.DATEONLY,
itdh__qadt04: Sequelize.DATEONLY,
itdh__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh__qadl03: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh__qadi01: Sequelize.INTEGER,
itdh__qadi02: Sequelize.INTEGER,
itdh_bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_btb_type: Sequelize.STRING,
itdh_btb_po: Sequelize.STRING,
itdh_btb_pod_line: Sequelize.INTEGER,
itdh_btb_vend: Sequelize.STRING,
itdh_exp_del: Sequelize.DATEONLY,
itdh_dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_cfg_type: Sequelize.STRING,
itdh_div: Sequelize.STRING,
itdh_pl_priority: Sequelize.INTEGER,
itdh_prig1: Sequelize.STRING,
itdh_prig2: Sequelize.STRING,
itdh__qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_sub: Sequelize.STRING,
itdh_dsc_sub: Sequelize.STRING,
itdh_dsc_project: Sequelize.STRING,
itdh_qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
itdh_cum_time: Sequelize.INTEGER,
itdh_ship_part: Sequelize.STRING,
itdh_promise_date: Sequelize.DATEONLY,
itdh_charge_type: Sequelize.STRING,
itdh_order_category: Sequelize.STRING,
itdh_modelyr: Sequelize.STRING,
itdh_custref: Sequelize.STRING,
itdh_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_max_aging_days: Sequelize.INTEGER,
itdh_consign_loc: Sequelize.STRING,
itdh_intrans_loc: Sequelize.STRING,
itdh_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
itdh_req_time: Sequelize.STRING,


itdh_domain: {
    type: Sequelize.STRING,
    defaultValue: 'zitouni'
},
oid_itdh_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
...base,
    },
    {
        tableName: "itdh_det",
    }
)
export default InvoiceOrderTempDetail
