import { Container } from 'typedi';
import Sequelize from 'sequelize';
import base from './base';
import Sequence from './sequence';


const sequelize = Container.get('sequelize');

const InvoiceOrder = sequelize.define(
    "invoice-Order",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true,

        },
        ih_inv_nbr: {
            type: Sequelize.STRING,
            unique: true,
        },
        ih_bill: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
        ih_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
	
		ih_category: {
			type: Sequelize.STRING,
			references: {
			  model: 'seq_mstr',
			  key: 'seq_seq',
			},
          },
        ih_nbr: Sequelize.STRING,
        ih_ship: Sequelize.STRING,
        ih_inv_date: Sequelize.DATEONLY,
        ih_ord_date: Sequelize.DATEONLY,
		ih_req_date: Sequelize.DATEONLY,
		ih_due_date: Sequelize.DATEONLY,
		ih_rmks: Sequelize.STRING,
		ih_cr_terms: Sequelize.STRING,
		ih_fob: Sequelize.STRING,
		ih_po: Sequelize.STRING,
		ih_shipvia: Sequelize.STRING,
		ih_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_print_so: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_pr_list: Sequelize.STRING,
		ih_xslspsn: Sequelize.STRING,
		ih_source: Sequelize.STRING,
		ih_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_cr_card: Sequelize.STRING,
		ih_print_pl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_cr_init: Sequelize.STRING,
		ih_stat: Sequelize.STRING,
		ih__qad01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qad02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qad03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_tax_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_prepaid: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_to_inv: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_invoiced: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_ar_acct: Sequelize.STRING,
		ih_ar_cc: Sequelize.STRING,
		
		ih_ship_date: Sequelize.DATEONLY,
		ih_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_cmtindx: Sequelize.INTEGER,
		ih__qad04: Sequelize.INTEGER,
		ih_user1: Sequelize.STRING,
		ih_user2: Sequelize.STRING,
		ih_curr: Sequelize.STRING,
		ih_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_lang: Sequelize.STRING,
		ih_type: Sequelize.STRING,
		ih_conf_date: Sequelize.DATEONLY,
		ih_rev: Sequelize.INTEGER,
		ih_bol: Sequelize.STRING,
		ih__qad05: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_fst_id: Sequelize.STRING,
		ih_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_tax_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_trl1_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_trl1_cd: Sequelize.STRING,
		ih_trl2_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_trl2_cd: Sequelize.STRING,
		ih_trl3_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_trl3_cd: Sequelize.STRING,
		ih_weight: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_weight_um: Sequelize.STRING,
		ih_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_size_um: Sequelize.STRING,
		ih_cartons: Sequelize.INTEGER,
		ih_site: Sequelize.STRING,
		ih_pst_id: Sequelize.STRING,
		ih_cncl_date: Sequelize.DATEONLY,
		ih_quote: Sequelize.STRING,
		ih_taxc: Sequelize.STRING,
		ih__chr01: Sequelize.STRING,
		ih__chr02: Sequelize.STRING,
		ih__chr03: Sequelize.STRING,
		ih__chr04: Sequelize.STRING,
		ih__chr05: Sequelize.STRING,
		ih__chr06: Sequelize.STRING,
		ih__chr07: Sequelize.STRING,
		ih__chr08: Sequelize.STRING,
		ih__chr09: Sequelize.STRING,
		ih__chr10: Sequelize.STRING,
		ih__dte01: Sequelize.DATEONLY,
		ih__dte02: Sequelize.DATEONLY,
		ih__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_credit: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_inv_cr: Sequelize.STRING,
		ih_project: Sequelize.STRING,
		ih_channel: Sequelize.STRING,
		ih_pst_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_fr_list: Sequelize.STRING,
		ih_fr_terms: Sequelize.STRING,
		ih_slspsn: Sequelize.STRING,
		ih_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_inv_mthd: Sequelize.STRING,
		ih_fix_rate: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_print_bl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_userid: Sequelize.STRING,
		ih_tax_date: Sequelize.DATEONLY,
        ih_fsm_type: Sequelize.STRING,
		ih_conrep: Sequelize.STRING,
		ih_bank: Sequelize.STRING,
		ih_tax_env: Sequelize.STRING,
		ih_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_fr_min_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_pr_list2: Sequelize.STRING,
		ih_tax_usage: Sequelize.STRING,
		ih_sa_nbr: Sequelize.STRING,
		ih_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_sch_mthd: Sequelize.STRING,
		ih_pricing_dt: Sequelize.DATEONLY,
		ih_priced_dt: Sequelize.DATEONLY,
		ih_ca_nbr: Sequelize.STRING,
		ih_eng_code: Sequelize.STRING,
		ih_fcg_code: Sequelize.STRING,
		ih_ship_eng: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_crprlist: Sequelize.STRING,
		ih__qadc01: Sequelize.STRING,
		ih__qadc02: Sequelize.STRING,
		ih__qadc03: Sequelize.STRING,
		ih__qadc04: Sequelize.STRING,
		ih__qadc05: Sequelize.STRING,
		ih__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_incl_iss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih__qadi01: Sequelize.INTEGER,
		ih__qadi02: Sequelize.INTEGER,
		ih__qadi03: Sequelize.INTEGER,
		ih__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qadt01: Sequelize.DATEONLY,
		ih__qadt02: Sequelize.DATEONLY,
		ih__qadt03: Sequelize.DATEONLY,
		ih_auth_days: Sequelize.INTEGER,
		ih_cum_acct: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_merge_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_ship_cmplt: Sequelize.INTEGER,
		ih_bump_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_primary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_cust_po: Sequelize.STRING,
		ih_secondary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_ship_po: Sequelize.STRING,
		ih_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih_ex_ratetype: Sequelize.STRING,
		ih_div: Sequelize.STRING,
		ih_exru_seq: Sequelize.INTEGER,
		ih_app_owner: Sequelize.STRING,
		ih_ar_sub: Sequelize.STRING,
		ih_seq_order: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_inc_in_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_firm_seq_days: Sequelize.INTEGER,
		ih_prep_tax: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ih__qadl04: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_custref_val: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_max_aging_days: Sequelize.INTEGER,
		ih_consign_loc: Sequelize.STRING,
		ih_intrans_loc: Sequelize.STRING,
		ih_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_revenue: Sequelize.STRING,
		ih_fsaccr_acct: Sequelize.STRING,
		ih_fsaccr_sub: Sequelize.STRING,
		ih_fsaccr_cc: Sequelize.STRING,
		ih_fsdef_acct: Sequelize.STRING,
		ih_fsdef_sub: Sequelize.STRING,
		ih_fsdef_cc: Sequelize.STRING,
		ih_manual_fr_terms: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ih_req_time: Sequelize.STRING,
		ih_domain: {type: Sequelize.STRING,	defaultValue: 'zitouni'	},
		oid_ih_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
		...base,
			},
			{
				tableName: "ih_hist",
			}
		)
	InvoiceOrder.addHook('beforeCreate', async (instance, option) => {
		if(instance.ih_inv_nbr == null) {
			const seq = await Sequence.findOne({ where: { seq_seq: instance.ih_category, seq_type: "IV"  } });
			instance.ih_inv_nbr = `${seq.seq_prefix}-${Number(seq.seq_curr_val)+1}`;
			await Sequence.update({ seq_curr_val: Number(seq.seq_curr_val )+1 }, { where: { seq_type: "IV", seq_seq: instance.ih_category } });
		}
	});
export default InvoiceOrder;
