import { Container } from 'typedi';
import Sequelize from 'sequelize';
import base from './base';
import Sequence from './sequence';


const sequelize = Container.get('sequelize');

const InvoiceOrderTemp = sequelize.define(
    "invoice-Order-Temp",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true,

        },
        ith_inv_nbr: {
            type: Sequelize.STRING,
            unique: true,
        },
        ith_bill: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
        ith_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
	
		ith_category: {
			type: Sequelize.STRING,
			references: {
			  model: 'seq_mstr',
			  key: 'seq_seq',
			},
          },
        ith_nbr: Sequelize.STRING,
        ith_ship: Sequelize.STRING,
        ith_inv_date: Sequelize.DATEONLY,
        ith_ord_date: Sequelize.DATEONLY,
		ith_req_date: Sequelize.DATEONLY,
		ith_due_date: Sequelize.DATEONLY,
		ith_rmks: Sequelize.STRING,
		ith_cr_terms: Sequelize.STRING,
		ith_fob: Sequelize.STRING,
		ith_po: Sequelize.STRING,
		ith_shipvia: Sequelize.STRING,
		ith_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_print_so: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_pr_list: Sequelize.STRING,
		ith_xslspsn: Sequelize.STRING,
		ith_source: Sequelize.STRING,
		ith_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_cr_card: Sequelize.STRING,
		ith_print_pl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_cr_init: Sequelize.STRING,
		ith_stat: Sequelize.STRING,
		ith__qad01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qad02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qad03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_tax_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_prepaid: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_to_inv: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_invoiced: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_ar_acct: Sequelize.STRING,
		ith_ar_cc: Sequelize.STRING,
		
		ith_ship_date: Sequelize.DATEONLY,
		ith_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_cmtindx: Sequelize.INTEGER,
		ith__qad04: Sequelize.INTEGER,
		ith_user1: Sequelize.STRING,
		ith_user2: Sequelize.STRING,
		ith_curr: Sequelize.STRING,
		ith_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_lang: Sequelize.STRING,
		ith_type: Sequelize.STRING,
		ith_conf_date: Sequelize.DATEONLY,
		ith_rev: Sequelize.INTEGER,
		ith_bol: Sequelize.STRING,
		ith__qad05: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_fst_id: Sequelize.STRING,
		ith_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_tax_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_trl1_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_trl1_cd: Sequelize.STRING,
		ith_trl2_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_trl2_cd: Sequelize.STRING,
		ith_trl3_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_trl3_cd: Sequelize.STRING,
		ith_weight: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_weight_um: Sequelize.STRING,
		ith_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_size_um: Sequelize.STRING,
		ith_cartons: Sequelize.INTEGER,
		ith_site: Sequelize.STRING,
		ith_pst_id: Sequelize.STRING,
		ith_cncl_date: Sequelize.DATEONLY,
		ith_quote: Sequelize.STRING,
		ith_taxc: Sequelize.STRING,
		ith__chr01: Sequelize.STRING,
		ith__chr02: Sequelize.STRING,
		ith__chr03: Sequelize.STRING,
		ith__chr04: Sequelize.STRING,
		ith__chr05: Sequelize.STRING,
		ith__chr06: Sequelize.STRING,
		ith__chr07: Sequelize.STRING,
		ith__chr08: Sequelize.STRING,
		ith__chr09: Sequelize.STRING,
		ith__chr10: Sequelize.STRING,
		ith__dte01: Sequelize.DATEONLY,
		ith__dte02: Sequelize.DATEONLY,
		ith__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_credit: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_inv_cr: Sequelize.STRING,
		ith_project: Sequelize.STRING,
		ith_channel: Sequelize.STRING,
		ith_pst_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_fr_list: Sequelize.STRING,
		ith_fr_terms: Sequelize.STRING,
		ith_slspsn: Sequelize.STRING,
		ith_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_inv_mthd: Sequelize.STRING,
		ith_fix_rate: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_print_bl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_userid: Sequelize.STRING,
		ith_tax_date: Sequelize.DATEONLY,
        ith_fsm_type: Sequelize.STRING,
		ith_conrep: Sequelize.STRING,
		ith_bank: Sequelize.STRING,
		ith_tax_env: Sequelize.STRING,
		ith_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_fr_min_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_pr_list2: Sequelize.STRING,
		ith_tax_usage: Sequelize.STRING,
		ith_sa_nbr: Sequelize.STRING,
		ith_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_sch_mthd: Sequelize.STRING,
		ith_pricing_dt: Sequelize.DATEONLY,
		ith_priced_dt: Sequelize.DATEONLY,
		ith_ca_nbr: Sequelize.STRING,
		ith_eng_code: Sequelize.STRING,
		ith_fcg_code: Sequelize.STRING,
		ith_ship_eng: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_crprlist: Sequelize.STRING,
		ith__qadc01: Sequelize.STRING,
		ith__qadc02: Sequelize.STRING,
		ith__qadc03: Sequelize.STRING,
		ith__qadc04: Sequelize.STRING,
		ith__qadc05: Sequelize.STRING,
		ith__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_incl_iss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith__qadi01: Sequelize.INTEGER,
		ith__qadi02: Sequelize.INTEGER,
		ith__qadi03: Sequelize.INTEGER,
		ith__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qadt01: Sequelize.DATEONLY,
		ith__qadt02: Sequelize.DATEONLY,
		ith__qadt03: Sequelize.DATEONLY,
		ith_auth_days: Sequelize.INTEGER,
		ith_cum_acct: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_merge_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_ship_cmplt: Sequelize.INTEGER,
		ith_bump_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_primary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_cust_po: Sequelize.STRING,
		ith_secondary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_ship_po: Sequelize.STRING,
		ith_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith_ex_ratetype: Sequelize.STRING,
		ith_div: Sequelize.STRING,
		ith_exru_seq: Sequelize.INTEGER,
		ith_app_owner: Sequelize.STRING,
		ith_ar_sub: Sequelize.STRING,
		ith_seq_order: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_inc_in_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_firm_seq_days: Sequelize.INTEGER,
		ith_prep_tax: {type: Sequelize.DECIMAL, defaultValue : 0  },
		ith__qadl04: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_custref_val: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_max_aging_days: Sequelize.INTEGER,
		ith_consign_loc: Sequelize.STRING,
		ith_intrans_loc: Sequelize.STRING,
		ith_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_revenue: Sequelize.STRING,
		ith_fsaccr_acct: Sequelize.STRING,
		ith_fsaccr_sub: Sequelize.STRING,
		ith_fsaccr_cc: Sequelize.STRING,
		ith_fsdef_acct: Sequelize.STRING,
		ith_fsdef_sub: Sequelize.STRING,
		ith_fsdef_cc: Sequelize.STRING,
		ith_manual_fr_terms: {type: Sequelize.BOOLEAN, defaultValue : false  },
		ith_req_time: Sequelize.STRING,
		ith_domain: {type: Sequelize.STRING,	defaultValue: 'zitouni'	},
		oid_ith_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
		...base,
			},
			{
				tableName: "ith_hist",
			}
		)
	InvoiceOrderTemp.addHook('beforeCreate', async (instance, option) => {
	const seq = await Sequence.findOne({ where: { seq_seq: instance.ith_category, seq_type: "IV"  } });
	instance.ith_inv_nbr = `${seq.seq_prefix}-${Number(seq.seq_curr_val)+1}`;
	await Sequence.update({ seq_curr_val: Number(seq.seq_curr_val )+1 }, { where: {seq_type: "IV", seq_seq: instance.ith_category } });
	});
export default InvoiceOrderTemp;
