import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const OperationHistory = sequelize.define(
    "OperationHistory",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        op_trnbr: Sequelize.INTEGER,
        op_type: Sequelize.STRING, 
        op_date: Sequelize.DATEONLY,
        op_emp: Sequelize.STRING, 
        op_wo_nbr: Sequelize.STRING,
           
        op_wo_op: Sequelize.INTEGER,
        op_act_setup: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_act_run: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_qty_wip: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_qty_comp: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_qty_rjct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_qty_rwrk: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_sub_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_wkctr: Sequelize.STRING, 
        op_wo_lot:{
            type: Sequelize.INTEGER,
            references: {
                model: "wo_mstr",
                key: "id",
            },
        },
        op_lbr_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_rsn: Sequelize.STRING, 
        op_rsn_rjct: Sequelize.STRING, 
        op_rsn_rwrk: Sequelize.STRING, 
        op_part:{
            type: Sequelize.STRING,
            references: {
                model: "pt_mstr",
                key: "pt_part",
            },
        },
        op_bdn_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op__qad01: Sequelize.STRING, 
        op__qad04: Sequelize.STRING, 
        op_project: Sequelize.STRING, 
        op_lbr_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_bdn_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_std_run: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_std_setup: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_wo_serial: Sequelize.STRING, 
        op_shift: Sequelize.STRING, 
        op_sub_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_po_nbr: Sequelize.STRING, 
        op_dept: Sequelize.STRING, 
        op_earn: Sequelize.STRING, 
        op_comment: Sequelize.STRING, 
        op_mch: Sequelize.STRING, 
        op_milestone: {type: Sequelize.BOOLEAN, defaultValue : false  },
        op_tran_date: Sequelize.DATEONLY,
        op_pay_calc: {type: Sequelize.BOOLEAN, defaultValue : false  },
        op_lbr_ovhd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_act_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_act_units: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_std_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_std_units: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_cmtindx: Sequelize.INTEGER,
        op_tool: Sequelize.STRING, 
        op_pro_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_user1: Sequelize.STRING, 
        op_user2: Sequelize.STRING, 
        op__qad05: Sequelize.STRING, 
        op__qad06: Sequelize.STRING, 
        op__qad07: Sequelize.STRING, 
        op__qad08: Sequelize.STRING, 
        op__qad02: Sequelize.STRING, 
        op__qad03: Sequelize.STRING, 
        op__chr01: Sequelize.STRING, 
        op__chr02: Sequelize.STRING, 
        op__chr03: Sequelize.STRING, 
        op__chr04: Sequelize.STRING, 
        op__chr05: Sequelize.STRING, 
        op__dte01: Sequelize.DATEONLY,
        op__dte02: Sequelize.DATEONLY,
        op__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        op_site: {
            type: Sequelize.STRING,
            references: {
                model: "si_mstr",
                key: "si_site",
            },
        },
        op_program: Sequelize.STRING, 
        op_time: Sequelize.INTEGER,
        op_userid: Sequelize.STRING, 
        op_sa_nbr: Sequelize.STRING, 
        op_fsm_type: Sequelize.STRING, 
        op_line: Sequelize.STRING, 
        op_rsn_down: Sequelize.STRING, 
        op_from_op: Sequelize.INTEGER,
        op_to_op: Sequelize.INTEGER,
        op_qty_scrap: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_qty_adjust: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_rsn_adjust: Sequelize.STRING, 
        op_fsc_code: Sequelize.STRING, 
        op_fcg_code: Sequelize.STRING, 
        op_eng_area: Sequelize.STRING, 
        op_ca_int_type: Sequelize.STRING, 
        op_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_curr: Sequelize.STRING, 
        op_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_flbr_std: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_flvrte_accr: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_flvrte_post: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_svc_type: Sequelize.STRING, 
        op_sv_code: Sequelize.STRING, 
        op_itm_line: Sequelize.INTEGER,
        op_ca_opn_date: Sequelize.DATEONLY,
        op_flbr_cstd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_eng_code: Sequelize.STRING, 
        op_sad_line: Sequelize.INTEGER,
        op_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_ex_ratetype: Sequelize.STRING, 
        op_exru_seq: Sequelize.INTEGER,
        op_wip_lotser: Sequelize.STRING, 
        op_wip_ref: Sequelize.STRING, 
        op_rsn_scrap: Sequelize.STRING, 
        op_userc03: Sequelize.STRING, 
        op_useri01: Sequelize.INTEGER,
        op_userd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        op_userl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        op_usert01: Sequelize.DATEONLY,
        
        op_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        oid_op_hist: {type: Sequelize.DECIMAL, defaultValue : 0  },
        ...base,
    },
    {
        tableName: "op_hist",
    }
)
export default OperationHistory
