import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const PurchaseOrderGlasses = sequelize.define(
    "PurchaseOrderGlasses",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        podg_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "po_mstr",
                key: "po_nbr",
            },
        },
        podg_line: Sequelize.INTEGER,
        podg_part: {
            type: Sequelize.STRING,
            references:{
                model: "gls_mstr",
                key: "gls_part",
            },

        },
        podg_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
        podg_due_date: Sequelize.DATEONLY,
        podg_qty_ord: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_qty_rcvd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_pur_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_so_job: Sequelize.STRING,
        podg_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        podg_cost_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_acct: Sequelize.STRING,
        podg_per_date: Sequelize.DATEONLY,
        podg_type: Sequelize.STRING,
        podg_insp_rqd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_wo_lot: Sequelize.STRING,
        podg_vpart: Sequelize.STRING,
        podg_need: Sequelize.DATEONLY,
        podg_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_desc: Sequelize.STRING,
        podg_cc: Sequelize.STRING,
        podg__qad04: Sequelize.STRING,
        podg_um: Sequelize.STRING,
        podg_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_req_nbr: Sequelize.STRING,
        podg__qad10: Sequelize.STRING,
        podg_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_loc: Sequelize.STRING,
        podg_serial: Sequelize.STRING,
        podg_op: Sequelize.INTEGER,
        podg_contract: Sequelize.STRING,
        podg_status: Sequelize.STRING,
        podg_rev: Sequelize.STRING,
        podg_cmtindx: Sequelize.INTEGER,
        podg_req_line: Sequelize.INTEGER,
        podg_project: Sequelize.STRING,
        podg_ps_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_cst_up: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_cyl:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
        podg_sph:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
        podg_add:{type: Sequelize.DECIMAL }, 
        podg_rum: Sequelize.STRING,
        podg_user1: Sequelize.STRING,
        podg_user2: Sequelize.STRING,
        podg_vat: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg__qad16: Sequelize.STRING,
        podg__qad06: Sequelize.STRING,
        podg_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg__qad13: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg__qad07: Sequelize.STRING,
        podg_pay_um: Sequelize.STRING,
        podg_pum_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg__qad15: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_site: Sequelize.STRING,
        podg_rum_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_qty_rtnd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_blanket: Sequelize.STRING,
        podg_blnkt_ln: Sequelize.INTEGER,
        podg__qad01: Sequelize.DATEONLY,
        podg__qad02: Sequelize.INTEGER,
        podg__qad03: Sequelize.STRING,
        podg__qad05: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg__qad08: Sequelize.DATEONLY,
        podg__qad09: Sequelize.INTEGER,
        podg__qad11: Sequelize.STRING,
        podg__qad12: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg__qad14: Sequelize.DATEONLY,
        podg_rel_nbr: Sequelize.INTEGER,
        podg_rel_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_reason: Sequelize.STRING,
        podg_request: Sequelize.STRING,
        podg_approve: Sequelize.STRING,
        podg__chr01: Sequelize.STRING,
        podg__chr02: Sequelize.STRING,
        podg__chr03: Sequelize.STRING,
        podg__chr04: Sequelize.STRING,
        podg__chr05: Sequelize.STRING,
        podg__chr06: Sequelize.STRING,
        podg__chr07: Sequelize.STRING,
        podg__chr08: Sequelize.STRING,
        podg__chr09: Sequelize.STRING,
        podg__chr10: Sequelize.STRING,
        podg__dte01: Sequelize.DATEONLY,
        podg__dte02: Sequelize.DATEONLY,
        podg__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_curr_rlse_id: Sequelize.STRING,
        podg_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_cum_date: Sequelize.DATEONLY,
        podg_contr_id: Sequelize.STRING,
        podg_apr_code: Sequelize.STRING,
        podg_taxc: Sequelize.STRING,
        podg_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_rma_type: Sequelize.STRING,
        podg_po_site: Sequelize.STRING,
        podg_po_db: Sequelize.STRING,
        podg_firm_weeks: Sequelize.INTEGER,
        podg_mrp_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_raw_weeks: Sequelize.INTEGER,
        podg_fab_weeks: Sequelize.INTEGER,
        podg_ship_weeks: Sequelize.INTEGER,
        podg_plan_weeks: Sequelize.INTEGER,
        podg_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_fsm_type: Sequelize.STRING,
        podg_sd_pat: Sequelize.STRING,
        podg_sd_time: Sequelize.STRING,
        podg_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_pkg_code: Sequelize.STRING,
        podg_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_sch_data: Sequelize.STRING,
        podg_rlse_nbr: Sequelize.INTEGER,
        podg_plan_days: Sequelize.INTEGER,
        podg_plan_mths: Sequelize.INTEGER,
        podg_firm_days: Sequelize.INTEGER,
        podg_start_eff: Sequelize.DATEONLY,
        podg_end_eff: Sequelize.DATEONLY,
        podg_raw_days: Sequelize.INTEGER,
        podg_fab_days: Sequelize.INTEGER,
        podg_tax_usage: Sequelize.STRING,
        podg_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_pr_list: Sequelize.STRING,
        podg_dock: Sequelize.STRING,
        podg_pastdue: Sequelize.STRING,
        podg_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_drp_ref: Sequelize.STRING,
        podg_tax_env: Sequelize.STRING,
        podg_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_fr_list: Sequelize.STRING,
        podg_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_sftylt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_sftylt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_lot_next: Sequelize.STRING,
        podg_lot_rcpt: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_grade: Sequelize.STRING,
        podg_expire: Sequelize.DATEONLY,
        podg_rctstat: Sequelize.STRING,
        podg_assay: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_rctstat_active: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_pricing_dt: Sequelize.DATEONLY,
        podg_pr_lst_tp: Sequelize.INTEGER,
        podg_ers_opt: Sequelize.INTEGER,
        podg__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
        podg_sod_line: Sequelize.INTEGER,
        podg_so_status: Sequelize.STRING,
        podg_sub_ship_date: Sequelize.DATEONLY,
        podg_sub_type: Sequelize.STRING,
        podg_sub: Sequelize.STRING,
        podg_wip_lotser: Sequelize.STRING,
        podg_pjs_line: Sequelize.INTEGER,
        podg_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_max_aging_days: Sequelize.INTEGER,
        podg_multi_due_dates: {type: Sequelize.BOOLEAN, defaultValue : false  },
        podg_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        oid_podg_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
        ...base,
    },
    {
        tableName: "podg_det",
    }
)
export default PurchaseOrderGlasses
