import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const PurchaseOrderDetail = sequelize.define(
    "PurchaseOrderDetail",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        pod_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "po_mstr",
                key: "po_nbr",
            },
        },
        pod_line: Sequelize.INTEGER,
        pod_part: {
            type: Sequelize.STRING,
            references:{
                model: "pt_mstr",
                key: "pt_part",
            },

        },
        pod_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
        pod_due_date: Sequelize.DATEONLY,
        pod_qty_ord: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_qty_rcvd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_pur_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_so_job: Sequelize.STRING,
        pod_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        pod_cost_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_acct: Sequelize.STRING,
        pod_per_date: Sequelize.DATEONLY,
        pod_type: Sequelize.STRING,
        pod_insp_rqd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_wo_lot: Sequelize.STRING,
        pod_vpart: Sequelize.STRING,
        pod_need: Sequelize.DATEONLY,
        pod_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_desc: Sequelize.STRING,
        pod_cc: Sequelize.STRING,
        pod__qad04: Sequelize.STRING,
        pod_um: Sequelize.STRING,
        pod_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_req_nbr: Sequelize.STRING,
        pod__qad10: Sequelize.STRING,
        pod_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_loc: Sequelize.STRING,
        pod_serial: Sequelize.STRING,
        pod_op: Sequelize.INTEGER,
        pod_contract: Sequelize.STRING,
        pod_status: Sequelize.STRING,
        pod_rev: Sequelize.STRING,
        pod_cmtindx: Sequelize.INTEGER,
        pod_req_line: Sequelize.INTEGER,
        pod_project: Sequelize.STRING,
        pod_ps_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_cst_up: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_rum: Sequelize.STRING,
        pod_user1: Sequelize.STRING,
        pod_user2: Sequelize.STRING,
        pod_vat: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod__qad16: Sequelize.STRING,
        pod__qad06: Sequelize.STRING,
        pod_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod__qad13: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod__qad07: Sequelize.STRING,
        pod_pay_um: Sequelize.STRING,
        pod_pum_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod__qad15: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_site: Sequelize.STRING,
        pod_rum_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_qty_rtnd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_blanket: Sequelize.STRING,
        pod_blnkt_ln: Sequelize.INTEGER,
        pod__qad01: Sequelize.DATEONLY,
        pod__qad02: Sequelize.INTEGER,
        pod__qad03: Sequelize.STRING,
        pod__qad05: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod__qad08: Sequelize.DATEONLY,
        pod__qad09: Sequelize.INTEGER,
        pod__qad11: Sequelize.STRING,
        pod__qad12: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod__qad14: Sequelize.DATEONLY,
        pod_rel_nbr: Sequelize.INTEGER,
        pod_rel_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_reason: Sequelize.STRING,
        pod_request: Sequelize.STRING,
        pod_approve: Sequelize.STRING,
        pod__chr01: Sequelize.STRING,
        pod__chr02: Sequelize.STRING,
        pod__chr03: Sequelize.STRING,
        pod__chr04: Sequelize.STRING,
        pod__chr05: Sequelize.STRING,
        pod__chr06: Sequelize.STRING,
        pod__chr07: Sequelize.STRING,
        pod__chr08: Sequelize.STRING,
        pod__chr09: Sequelize.STRING,
        pod__chr10: Sequelize.STRING,
        pod__dte01: Sequelize.DATEONLY,
        pod__dte02: Sequelize.DATEONLY,
        pod__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_curr_rlse_id: Sequelize.STRING,
        pod_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_cum_date: Sequelize.DATEONLY,
        pod_contr_id: Sequelize.STRING,
        pod_apr_code: Sequelize.STRING,
        pod_taxc: Sequelize.STRING,
        pod_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_rma_type: Sequelize.STRING,
        pod_po_site: Sequelize.STRING,
        pod_po_db: Sequelize.STRING,
        pod_firm_weeks: Sequelize.INTEGER,
        pod_mrp_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_raw_weeks: Sequelize.INTEGER,
        pod_fab_weeks: Sequelize.INTEGER,
        pod_ship_weeks: Sequelize.INTEGER,
        pod_plan_weeks: Sequelize.INTEGER,
        pod_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_fsm_type: Sequelize.STRING,
        pod_sd_pat: Sequelize.STRING,
        pod_sd_time: Sequelize.STRING,
        pod_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_pkg_code: Sequelize.STRING,
        pod_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_sch_data: Sequelize.STRING,
        pod_rlse_nbr: Sequelize.INTEGER,
        pod_plan_days: Sequelize.INTEGER,
        pod_plan_mths: Sequelize.INTEGER,
        pod_firm_days: Sequelize.INTEGER,
        pod_start_eff: Sequelize.DATEONLY,
        pod_end_eff: Sequelize.DATEONLY,
        pod_raw_days: Sequelize.INTEGER,
        pod_fab_days: Sequelize.INTEGER,
        pod_tax_usage: Sequelize.STRING,
        pod_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_pr_list: Sequelize.STRING,
        pod_dock: Sequelize.STRING,
        pod_pastdue: Sequelize.STRING,
        pod_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_drp_ref: Sequelize.STRING,
        pod_tax_env: Sequelize.STRING,
        pod_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_fr_list: Sequelize.STRING,
        pod_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_sftylt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_sftylt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_lot_next: Sequelize.STRING,
        pod_lot_rcpt: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_grade: Sequelize.STRING,
        pod_expire: Sequelize.DATEONLY,
        pod_rctstat: Sequelize.STRING,
        pod_assay: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_rctstat_active: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_pricing_dt: Sequelize.DATEONLY,
        pod_pr_lst_tp: Sequelize.INTEGER,
        pod_ers_opt: Sequelize.INTEGER,
        pod__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
        pod_sod_line: Sequelize.INTEGER,
        pod_so_status: Sequelize.STRING,
        pod_sub_ship_date: Sequelize.DATEONLY,
        pod_sub_type: Sequelize.STRING,
        pod_sub: Sequelize.STRING,
        pod_wip_lotser: Sequelize.STRING,
        pod_pjs_line: Sequelize.INTEGER,
        pod_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_max_aging_days: Sequelize.INTEGER,
        pod_multi_due_dates: {type: Sequelize.BOOLEAN, defaultValue : false  },
        pod_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        oid_pod_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
        ...base,
    },
    {
        tableName: "pod_det",
    }
)
export default PurchaseOrderDetail
