import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const saleOrderGlasses = sequelize.define(
    "saleorderGlasses",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        sodg_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "so_mstr",
                key: "so_nbr",
            },
        },
        sodg_line: Sequelize.INTEGER,
        sodg_part: {
            type: Sequelize.STRING,
            references:{
                model: "gls_mstr",
                key: "gls_part",
            },

        },

        sodg_tax_code: Sequelize.STRING,
           
        sodg_due_date: Sequelize.DATEONLY,
        sodg_per_date: Sequelize.DATEONLY,
        sodg_req_date: Sequelize.DATEONLY,
        sodg_cyl:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_sph:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_add:{type: Sequelize.DECIMAL }, 
        sodg_qty_ord:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_qty_ship:   {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_qty_inv:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_loc: Sequelize.STRING,
        sodg_type: Sequelize.STRING,
        sodg_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_sales_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_qty_chg:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
        sodg_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_acct: Sequelize.STRING,
        sodg_abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_serial: Sequelize.STRING,
        sodg_desc: Sequelize.STRING,
        sodg_um: Sequelize.STRING,
        sodg_cc: Sequelize.STRING,
        sodg_comment: Sequelize.STRING,
        sodg_lot: Sequelize.STRING,
        sodg_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_fa_nbr: Sequelize.STRING,
        sodg_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_project: Sequelize.STRING,
        sodg_cmtindx: Sequelize.INTEGER,
        sodg_custpart: Sequelize.STRING,
        sodg__qad01: Sequelize.INTEGER,
        sodg_status: Sequelize.STRING,
        sodg_xslspsn: Sequelize.STRING,
        sodg_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_dsc_acct: Sequelize.STRING,
        sodg_dsc_cc: Sequelize.STRING,
        sodg_list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_user1: Sequelize.STRING,
        sodg_user2: Sequelize.STRING,
        sodg_sob_rev: Sequelize.DATEONLY,
        sodg_sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_expire: Sequelize.DATEONLY,
        sodg__qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_taxc: Sequelize.STRING,
        sodg_inv_nbr: Sequelize.STRING,
        sodg_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_site: Sequelize.STRING,
        sodg_prodline: Sequelize.STRING,
        sodg_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg__chr01: Sequelize.STRING,
        sodg__chr02: Sequelize.STRING,
        sodg__chr03: Sequelize.STRING,
        sodg__chr04: Sequelize.STRING,
        sodg__chr05: Sequelize.STRING,
        sodg__chr06: Sequelize.STRING,
        sodg__chr07: Sequelize.STRING,
        sodg__chr08: Sequelize.STRING,
        sodg__chr09: Sequelize.STRING,
        sodg__chr10: Sequelize.STRING,
        sodg__dte01: Sequelize.DATEONLY,
        sodg__dte02: Sequelize.DATEONLY,
        sodg__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_curr_rlse_id: Sequelize.STRING,
        sodg_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_contr_id: Sequelize.STRING,
        sodg_pickdate: Sequelize.DATEONLY,
        sodg_confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_cum_date: Sequelize.DATEONLY,
        sodg_for: Sequelize.STRING,
        sodg_ref: Sequelize.STRING,
        sodg_qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_rma_type: Sequelize.STRING,
        sodg_owner: Sequelize.STRING,
        sodg_calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_slspsn: Sequelize.STRING,
        sodg_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_pkg_code: Sequelize.STRING,
        sodg_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_fsm_type: Sequelize.STRING,
        sodg_conrep: Sequelize.STRING,
        sodg_sch_data: Sequelize.STRING,
        sodg_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_rlse_nbr: Sequelize.INTEGER,
        sodg_start_eff: Sequelize.DATEONLY,
        sodg_end_eff: Sequelize.DATEONLY,
        sodg_dock: Sequelize.STRING,
        sodg_pr_list: Sequelize.STRING,
        sodg_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_out_po: Sequelize.STRING,
        sodg_raw_days: Sequelize.INTEGER,
        sodg_fab_days: Sequelize.INTEGER,
        sodg_tax_usage: Sequelize.STRING,
        sodg_rbkt_days: Sequelize.INTEGER,
        sodg_rbkt_weeks: Sequelize.INTEGER,
        sodg_rbkt_mths: Sequelize.INTEGER,
        sodg_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_pastdue: Sequelize.STRING,
        sodg_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_fr_wt_um: Sequelize.STRING,
        sodg_fr_class: Sequelize.STRING,
        sodg_fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_ship: Sequelize.STRING,
        sodg_sa_nbr: Sequelize.STRING,
        sodg_enduser: Sequelize.STRING,
        sodg_isb_loc: Sequelize.STRING,
        sodg_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_isb_ref: Sequelize.INTEGER,
        sodg_auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_drp_ref: Sequelize.STRING,
        sodg_tax_env: Sequelize.STRING,
        sodg_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_fr_list: Sequelize.STRING,
        sodg_pricing_dt: Sequelize.DATEONLY,
        sodg_act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_ca_line: Sequelize.INTEGER,
        sodg_qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_ca_nbr: Sequelize.STRING,
        sodg_qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_to_loc: Sequelize.STRING,
        sodg_to_site: Sequelize.STRING,
        sodg_to_ref: Sequelize.STRING,
        sodg_ln_ref: Sequelize.STRING,
        sodg_qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_sad_line: Sequelize.INTEGER,
        sodg_warr_start: Sequelize.DATEONLY,
        sodg_mod_userid: Sequelize.STRING,
        sodg_mod_date: Sequelize.DATEONLY,
        sodg_sv_code: Sequelize.STRING,
        sodg_alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_for_serial: Sequelize.STRING,
        sodg_override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg__qadc01: Sequelize.STRING,
        sodg__qadc02: Sequelize.STRING,
        sodg__qadc03: Sequelize.STRING,
        sodg__qadc04: Sequelize.STRING,
        sodg__qadt01: Sequelize.DATEONLY,
        sodg__qadt02: Sequelize.DATEONLY,
        sodg__qadt03: Sequelize.DATEONLY,
        sodg__qadt04: Sequelize.DATEONLY,
        sodg__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg__qadl03: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg__qadi01: Sequelize.INTEGER,
        sodg__qadi02: Sequelize.INTEGER,
        sodg_bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_btb_type: Sequelize.STRING,
        sodg_btb_po: Sequelize.STRING,
        sodg_btb_pod_line: Sequelize.INTEGER,
        sodg_btb_vend: Sequelize.STRING,
        sodg_exp_del: Sequelize.DATEONLY,
        sodg_dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_cfg_type: Sequelize.STRING,
        sodg_div: Sequelize.STRING,
        sodg_pl_priority: Sequelize.INTEGER,
        sodg_prig1: Sequelize.STRING,
        sodg_prig2: Sequelize.STRING,
        sodg__qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_sub: Sequelize.STRING,
        sodg_dsc_sub: Sequelize.STRING,
        sodg_dsc_project: Sequelize.STRING,
        sodg_qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
        sodg_cum_time: Sequelize.INTEGER,
        sodg_ship_part: Sequelize.STRING,
        sodg_promise_date: Sequelize.DATEONLY,
        sodg_charge_type: Sequelize.STRING,
        sodg_order_category: Sequelize.STRING,
        sodg_modelyr: Sequelize.STRING,
        sodg_custref: Sequelize.STRING,
        sodg_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_max_aging_days: Sequelize.INTEGER,
        sodg_consign_loc: Sequelize.STRING,
        sodg_intrans_loc: Sequelize.STRING,
        sodg_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
        sodg_req_time: Sequelize.STRING,


        sodg_domain: {
            type: Sequelize.STRING,
            defaultValue: 'zitouni'
        },
        oid_sodg_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
        ...base,
            },
    {
        tableName: "sodg_det",
    }
)
export default saleOrderGlasses
