import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const saleOrderDetail = sequelize.define(
    "saleorderDetail",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        sod_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "so_mstr",
                key: "so_nbr",
            },
        },
        sod_line: Sequelize.INTEGER,
        sod_part: {
            type: Sequelize.STRING,
            references:{
                model: "pt_mstr",
                key: "pt_part",
            },

        },

        sod_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
sod_due_date: Sequelize.DATEONLY,
sod_per_date: Sequelize.DATEONLY,
sod_req_date: Sequelize.DATEONLY,
sod_qty_ord:{type: Sequelize.DECIMAL, defaultValue : 0  }, 
sod_qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
sod_qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
sod_qty_ship:   {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_qty_inv:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
sod_loc: Sequelize.STRING,
sod_type: Sequelize.STRING,
sod_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_sales_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_qty_chg:  {type: Sequelize.DECIMAL, defaultValue : 0  }, 
sod_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_acct: Sequelize.STRING,
sod_abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_serial: Sequelize.STRING,
sod_desc: Sequelize.STRING,
sod_um: Sequelize.STRING,
sod_cc: Sequelize.STRING,
sod_comment: Sequelize.STRING,
sod_lot: Sequelize.STRING,
sod_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_fa_nbr: Sequelize.STRING,
sod_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_project: Sequelize.STRING,
sod_cmtindx: Sequelize.INTEGER,
sod_custpart: Sequelize.STRING,
sod__qad01: Sequelize.INTEGER,
sod_status: Sequelize.STRING,
sod_xslspsn: Sequelize.STRING,
sod_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_dsc_acct: Sequelize.STRING,
sod_dsc_cc: Sequelize.STRING,
sod_list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_user1: Sequelize.STRING,
sod_user2: Sequelize.STRING,
sod_sob_rev: Sequelize.DATEONLY,
sod_sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_expire: Sequelize.DATEONLY,
sod__qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_taxc: Sequelize.STRING,
sod_inv_nbr: Sequelize.STRING,
sod_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_site: Sequelize.STRING,
sod_prodline: Sequelize.STRING,
sod_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod__chr01: Sequelize.STRING,
sod__chr02: Sequelize.STRING,
sod__chr03: Sequelize.STRING,
sod__chr04: Sequelize.STRING,
sod__chr05: Sequelize.STRING,
sod__chr06: Sequelize.STRING,
sod__chr07: Sequelize.STRING,
sod__chr08: Sequelize.STRING,
sod__chr09: Sequelize.STRING,
sod__chr10: Sequelize.STRING,
sod__dte01: Sequelize.DATEONLY,
sod__dte02: Sequelize.DATEONLY,
sod__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_curr_rlse_id: Sequelize.STRING,
sod_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_contr_id: Sequelize.STRING,
sod_pickdate: Sequelize.DATEONLY,
sod_confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_cum_date: Sequelize.DATEONLY,
sod_for: Sequelize.STRING,
sod_ref: Sequelize.STRING,
sod_qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_rma_type: Sequelize.STRING,
sod_owner: Sequelize.STRING,
sod_calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_slspsn: Sequelize.STRING,
sod_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_pkg_code: Sequelize.STRING,
sod_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_fsm_type: Sequelize.STRING,
sod_conrep: Sequelize.STRING,
sod_sch_data: Sequelize.STRING,
sod_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_rlse_nbr: Sequelize.INTEGER,
sod_start_eff: Sequelize.DATEONLY,
sod_end_eff: Sequelize.DATEONLY,
sod_dock: Sequelize.STRING,
sod_pr_list: Sequelize.STRING,
sod_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_out_po: Sequelize.STRING,
sod_raw_days: Sequelize.INTEGER,
sod_fab_days: Sequelize.INTEGER,
sod_tax_usage: Sequelize.STRING,
sod_rbkt_days: Sequelize.INTEGER,
sod_rbkt_weeks: Sequelize.INTEGER,
sod_rbkt_mths: Sequelize.INTEGER,
sod_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_pastdue: Sequelize.STRING,
sod_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_fr_wt_um: Sequelize.STRING,
sod_fr_class: Sequelize.STRING,
sod_fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_ship: Sequelize.STRING,
sod_sa_nbr: Sequelize.STRING,
sod_enduser: Sequelize.STRING,
sod_isb_loc: Sequelize.STRING,
sod_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_isb_ref: Sequelize.INTEGER,
sod_auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_drp_ref: Sequelize.STRING,
sod_tax_env: Sequelize.STRING,
sod_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_fr_list: Sequelize.STRING,
sod_pricing_dt: Sequelize.DATEONLY,
sod_act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_ca_line: Sequelize.INTEGER,
sod_qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_ca_nbr: Sequelize.STRING,
sod_qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_to_loc: Sequelize.STRING,
sod_to_site: Sequelize.STRING,
sod_to_ref: Sequelize.STRING,
sod_ln_ref: Sequelize.STRING,
sod_qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_sad_line: Sequelize.INTEGER,
sod_warr_start: Sequelize.DATEONLY,
sod_mod_userid: Sequelize.STRING,
sod_mod_date: Sequelize.DATEONLY,
sod_sv_code: Sequelize.STRING,
sod_alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_for_serial: Sequelize.STRING,
sod_override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod__qadc01: Sequelize.STRING,
sod__qadc02: Sequelize.STRING,
sod__qadc03: Sequelize.STRING,
sod__qadc04: Sequelize.STRING,
sod__qadt01: Sequelize.DATEONLY,
sod__qadt02: Sequelize.DATEONLY,
sod__qadt03: Sequelize.DATEONLY,
sod__qadt04: Sequelize.DATEONLY,
sod__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod__qadl03: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod__qadi01: Sequelize.INTEGER,
sod__qadi02: Sequelize.INTEGER,
sod_bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_btb_type: Sequelize.STRING,
sod_btb_po: Sequelize.STRING,
sod_btb_pod_line: Sequelize.INTEGER,
sod_btb_vend: Sequelize.STRING,
sod_exp_del: Sequelize.DATEONLY,
sod_dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_cfg_type: Sequelize.STRING,
sod_div: Sequelize.STRING,
sod_pl_priority: Sequelize.INTEGER,
sod_prig1: Sequelize.STRING,
sod_prig2: Sequelize.STRING,
sod__qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_sub: Sequelize.STRING,
sod_dsc_sub: Sequelize.STRING,
sod_dsc_project: Sequelize.STRING,
sod_qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
sod_cum_time: Sequelize.INTEGER,
sod_ship_part: Sequelize.STRING,
sod_promise_date: Sequelize.DATEONLY,
sod_charge_type: Sequelize.STRING,
sod_order_category: Sequelize.STRING,
sod_modelyr: Sequelize.STRING,
sod_custref: Sequelize.STRING,
sod_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_max_aging_days: Sequelize.INTEGER,
sod_consign_loc: Sequelize.STRING,
sod_intrans_loc: Sequelize.STRING,
sod_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
sod_req_time: Sequelize.STRING,


sod_domain: {
    type: Sequelize.STRING,
    defaultValue: 'zitouni'
},
oid_sod_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
...base,
    },
    {
        tableName: "sod_det",
    }
)
export default saleOrderDetail
