import { Container } from 'typedi';
import Sequelize from 'sequelize';
import base from './base';
import Sequence from './sequence';


const sequelize = Container.get('sequelize');

const saleOrder = sequelize.define(
    "saleorder",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true,

        },
        so_nbr: {
            type: Sequelize.STRING,
            unique: true,
        },
        so_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
	
		so_category: {
			type: Sequelize.STRING,
			references: {
			  model: 'seq_mstr',
			  key: 'seq_seq',
			},
		  },
		so_ship: Sequelize.STRING,
		so_ord_date: Sequelize.DATEONLY,
		so_req_date: Sequelize.DATEONLY,
		so_due_date: Sequelize.DATEONLY,
		so_rmks: Sequelize.STRING,
		so_cr_terms: Sequelize.STRING,
		so_fob: Sequelize.STRING,
		so_po: Sequelize.STRING,
		so_shipvia: Sequelize.STRING,
		so_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_conf: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_print_so: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_inv_nbr: Sequelize.STRING,
		so_pr_list: Sequelize.STRING,
		so_xslspsn: Sequelize.STRING,
		so_source: Sequelize.STRING,
		so_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_cr_card: Sequelize.STRING,
		so_print_pl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_cr_init: Sequelize.STRING,
		so_stat: Sequelize.STRING,
		so__qad01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qad02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qad03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_tax_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_prepaid: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_to_inv: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_invoiced: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_ar_acct: Sequelize.STRING,
		so_ar_cc: Sequelize.STRING,
		so_inv_date: Sequelize.DATEONLY,
		so_ship_date: Sequelize.DATEONLY,
		so_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_cmtindx: Sequelize.INTEGER,
		so__qad04: Sequelize.INTEGER,
		so_user1: Sequelize.STRING,
		so_user2: Sequelize.STRING,
		so_curr: Sequelize.STRING,
		so_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_lang: Sequelize.STRING,
		so_type: Sequelize.STRING,
		so_conf_date: Sequelize.DATEONLY,
		so_rev: Sequelize.INTEGER,
		so_bol: Sequelize.STRING,
		so__qad05: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_fst_id: Sequelize.STRING,
		so_trl1_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_trl1_cd: Sequelize.STRING,
		so_trl2_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_trl2_cd: Sequelize.STRING,
		so_trl3_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_trl3_cd: Sequelize.STRING,
		so_weight: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_weight_um: Sequelize.STRING,
		so_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_size_um: Sequelize.STRING,
		so_cartons: Sequelize.INTEGER,
		so_site: Sequelize.STRING,
		so_pst_id: Sequelize.STRING,
		so_cncl_date: Sequelize.DATEONLY,
		so_quote: Sequelize.STRING,
		so_taxc: Sequelize.STRING,
		so__chr01: Sequelize.STRING,
		so__chr02: Sequelize.STRING,
		so__chr03: Sequelize.STRING,
		so__chr04: Sequelize.STRING,
		so__chr05: Sequelize.STRING,
		so__chr06: Sequelize.STRING,
		so__chr07: Sequelize.STRING,
		so__chr08: Sequelize.STRING,
		so__chr09: Sequelize.STRING,
		so__chr10: Sequelize.STRING,
		so__dte01: Sequelize.DATEONLY,
		so__dte02: Sequelize.DATEONLY,
		so__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_credit: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_inv_cr: Sequelize.STRING,
		so_project: Sequelize.STRING,
		so_channel: Sequelize.STRING,
		so_pst_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_fr_list: Sequelize.STRING,
		so_fr_terms: Sequelize.STRING,
		so_slspsn: Sequelize.STRING,
		so_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_inv_mthd: Sequelize.STRING,
		so_fix_rate: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_bill: Sequelize.STRING,
		so_print_bl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_userid: Sequelize.STRING,
		so_tax_date: Sequelize.DATEONLY,
		so_fsm_type: Sequelize.STRING,
		so_conrep: Sequelize.STRING,
		so_bank: Sequelize.STRING,
		so_tax_env: Sequelize.STRING,
		so_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_fr_min_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_pr_list2: Sequelize.STRING,
		so_tax_usage: Sequelize.STRING,
		so_sa_nbr: Sequelize.STRING,
		so_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_sch_mthd: Sequelize.STRING,
		so_pricing_dt: Sequelize.DATEONLY,
		so_priced_dt: Sequelize.DATEONLY,
		so_ca_nbr: Sequelize.STRING,
		so_eng_code: Sequelize.STRING,
		so_fcg_code: Sequelize.STRING,
		so_ship_eng: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_crprlist: Sequelize.STRING,
		so__qadc01: Sequelize.STRING,
		so__qadc02: Sequelize.STRING,
		so__qadc03: Sequelize.STRING,
		so__qadc04: Sequelize.STRING,
		so__qadc05: Sequelize.STRING,
		so__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_incl_iss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so__qadi01: Sequelize.INTEGER,
		so__qadi02: Sequelize.INTEGER,
		so__qadi03: Sequelize.INTEGER,
		so__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qadt01: Sequelize.DATEONLY,
		so__qadt02: Sequelize.DATEONLY,
		so__qadt03: Sequelize.DATEONLY,
		so_auth_days: Sequelize.INTEGER,
		so_cum_acct: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_merge_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_ship_cmplt: Sequelize.INTEGER,
		so_bump_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_primary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_cust_po: Sequelize.STRING,
		so_secondary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_ship_po: Sequelize.STRING,
		so_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_ex_ratetype: Sequelize.STRING,
		so_div: Sequelize.STRING,
		so_exru_seq: Sequelize.INTEGER,
		so_app_owner: Sequelize.STRING,
		so_ar_sub: Sequelize.STRING,
		so_seq_order: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_inc_in_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_firm_seq_days: Sequelize.INTEGER,
		so_prep_tax: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so__qadl04: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_custref_val: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_max_aging_days: Sequelize.INTEGER,
		so_consign_loc: Sequelize.STRING,
		so_intrans_loc: Sequelize.STRING,
		so_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_revenue: Sequelize.STRING,
		so_fsaccr_acct: Sequelize.STRING,
		so_fsaccr_sub: Sequelize.STRING,
		so_fsaccr_cc: Sequelize.STRING,
		so_fsdef_acct: Sequelize.STRING,
		so_fsdef_sub: Sequelize.STRING,
		so_fsdef_cc: Sequelize.STRING,
		so_manual_fr_terms: {type: Sequelize.BOOLEAN, defaultValue : false  },
		so_req_time: Sequelize.STRING,
		so_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_tax_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		so_domain: {type: Sequelize.STRING,	defaultValue: 'zitouni'	},
		oid_so_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
		...base,
			},
			{
				tableName: "so_mstr",
			}
		)
	saleOrder.addHook('beforeCreate', async (instance, option) => {
		
	const seq = await Sequence.findOne({ where: { seq_seq: instance.so_category, seq_type: "SO"  } });
	instance.so_nbr = `${seq.seq_prefix}-${Number(seq.seq_curr_val)+1}`;
	await Sequence.update({ seq_curr_val: Number(seq.seq_curr_val )+1 }, { where: { seq_type: "SO", seq_seq: instance.so_category } });
	});
export default saleOrder;
