import { Container } from 'typedi';
import Sequelize from 'sequelize';
import base from './base';
import Sequence from './sequence';


const sequelize = Container.get('sequelize');

const Visite = sequelize.define(
    "visite",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true,

        },
        vis_nbr: {
            type: Sequelize.STRING,
            unique: true,
        },
        vis_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
	
		vis_category: {
			type: Sequelize.STRING,
			references: {
			  model: 'seq_mstr',
			  key: 'seq_seq',
			},
		  },
		vis_ship: Sequelize.STRING,
        vis_so_nbr: Sequelize.STRING,
        vis_rcyl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vis_rsph: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vis_radd: {type: Sequelize.DECIMAL },
		vis_rprisme: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_rbase: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_recart: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_rhauteur: {type: Sequelize.DECIMAL, defaultValue : 0  },

		vis_raxe: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vis_lcyl: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vis_lsph: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vis_ladd: {type: Sequelize.DECIMAL },
		vis_lprisme: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_lbase: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_lecart: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_lhauteur: {type: Sequelize.DECIMAL, defaultValue : 0  },

		vis_laxe: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_ord_date: Sequelize.DATEONLY,
		vis_req_date: Sequelize.DATEONLY,
		vis_due_date: Sequelize.DATEONLY,
		vis_rmks: Sequelize.STRING,
		vis_cr_terms: Sequelize.STRING,
		vis_fob: Sequelize.STRING,
		vis_po: Sequelize.STRING,
		vis_shipvia: Sequelize.STRING,
		vis_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_conf: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_print_so: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_inv_nbr: Sequelize.STRING,
		vis_pr_list: Sequelize.STRING,
		vis_xslspsn: Sequelize.STRING,
		vis_source: Sequelize.STRING,
		vis_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_cr_card: Sequelize.STRING,
		vis_print_pl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_cr_init: Sequelize.STRING,
		vis_stat: Sequelize.STRING,
		vis__qad01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qad02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qad03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_tax_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_prepaid: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_to_inv: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_invoiced: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_ar_acct: Sequelize.STRING,
		vis_ar_cc: Sequelize.STRING,
		vis_inv_date: Sequelize.DATEONLY,
		vis_ship_date: Sequelize.DATEONLY,
		vis_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_cmtindx: Sequelize.INTEGER,
		vis__qad04: Sequelize.INTEGER,
		vis_user1: Sequelize.STRING,
		vis_user2: Sequelize.STRING,
		vis_curr: Sequelize.STRING,
		vis_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_lang: Sequelize.STRING,
		vis_type: Sequelize.STRING,
		vis_conf_date: Sequelize.DATEONLY,
		vis_rev: Sequelize.INTEGER,
		vis_bol: Sequelize.STRING,
		vis__qad05: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_fst_id: Sequelize.STRING,
		vis_trl1_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_trl1_cd: Sequelize.STRING,
		vis_trl2_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_trl2_cd: Sequelize.STRING,
		vis_trl3_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_trl3_cd: Sequelize.STRING,
		vis_weight: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_weight_um: Sequelize.STRING,
		vis_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_size_um: Sequelize.STRING,
		vis_cartons: Sequelize.INTEGER,
		vis_site: Sequelize.STRING,
		vis_pst_id: Sequelize.STRING,
		vis_cncl_date: Sequelize.DATEONLY,
		vis_quote: Sequelize.STRING,
		vis_taxc: Sequelize.STRING,
		vis__chr01: Sequelize.STRING,
		vis__chr02: Sequelize.STRING,
		vis__chr03: Sequelize.STRING,
		vis__chr04: Sequelize.STRING,
		vis__chr05: Sequelize.STRING,
		vis__chr06: Sequelize.STRING,
		vis__chr07: Sequelize.STRING,
		vis__chr08: Sequelize.STRING,
		vis__chr09: Sequelize.STRING,
		vis__chr10: Sequelize.STRING,
		vis__dte01: Sequelize.DATEONLY,
		vis__dte02: Sequelize.DATEONLY,
		vis__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_credit: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_inv_cr: Sequelize.STRING,
		vis_project: Sequelize.STRING,
		vis_channel: Sequelize.STRING,
		vis_pst_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_fr_list: Sequelize.STRING,
		vis_fr_terms: Sequelize.STRING,
		vis_slspsn: Sequelize.STRING,
		vis_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_inv_mthd: Sequelize.STRING,
		vis_fix_rate: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_bill: Sequelize.STRING,
		vis_print_bl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_userid: Sequelize.STRING,
		vis_tax_date: Sequelize.DATEONLY,
		vis_fsm_type: Sequelize.STRING,
		vis_conrep: Sequelize.STRING,
		vis_bank: Sequelize.STRING,
		vis_tax_env: Sequelize.STRING,
		vis_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_fr_min_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_pr_list2: Sequelize.STRING,
		vis_tax_usage: Sequelize.STRING,
		vis_sa_nbr: Sequelize.STRING,
		vis_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_sch_mthd: Sequelize.STRING,
		vis_pricing_dt: Sequelize.DATEONLY,
		vis_priced_dt: Sequelize.DATEONLY,
		vis_ca_nbr: Sequelize.STRING,
		vis_eng_code: Sequelize.STRING,
		vis_fcg_code: Sequelize.STRING,
		vis_ship_eng: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_crprlist: Sequelize.STRING,
		vis__qadc01: Sequelize.STRING,
		vis__qadc02: Sequelize.STRING,
		vis__qadc03: Sequelize.STRING,
		vis__qadc04: Sequelize.STRING,
		vis__qadc05: Sequelize.STRING,
		vis__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_incl_iss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis__qadi01: Sequelize.INTEGER,
		vis__qadi02: Sequelize.INTEGER,
		vis__qadi03: Sequelize.INTEGER,
		vis__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qadt01: Sequelize.DATEONLY,
		vis__qadt02: Sequelize.DATEONLY,
		vis__qadt03: Sequelize.DATEONLY,
		vis_auth_days: Sequelize.INTEGER,
		vis_cum_acct: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_merge_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_ship_cmplt: Sequelize.INTEGER,
		vis_bump_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_primary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_cust_po: Sequelize.STRING,
		vis_secondary: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_ship_po: Sequelize.STRING,
		vis_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_ex_ratetype: Sequelize.STRING,
		vis_div: Sequelize.STRING,
		vis_exru_seq: Sequelize.INTEGER,
		vis_app_owner: Sequelize.STRING,
		vis_ar_sub: Sequelize.STRING,
		vis_seq_order: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_inc_in_rss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_firm_seq_days: Sequelize.INTEGER,
		vis_prep_tax: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis__qadl04: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_custref_val: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_max_aging_days: Sequelize.INTEGER,
		vis_consign_loc: Sequelize.STRING,
		vis_intrans_loc: Sequelize.STRING,
		vis_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_revenue: Sequelize.STRING,
		vis_fsaccr_acct: Sequelize.STRING,
		vis_fsaccr_sub: Sequelize.STRING,
		vis_fsaccr_cc: Sequelize.STRING,
		vis_fsdef_acct: Sequelize.STRING,
		vis_fsdef_sub: Sequelize.STRING,
		vis_fsdef_cc: Sequelize.STRING,
		vis_manual_fr_terms: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vis_req_time: Sequelize.STRING,
		vis_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_tax_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vis_domain: {type: Sequelize.STRING,	defaultValue: 'zitouni'	},
		oid_vis_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
		...base,
			},
			{
				tableName: "vis_mstr",
			}
		)
	Visite.addHook('beforeCreate', async (instance, option) => {
		
	const seq = await Sequence.findOne({ where: { seq_seq: "VI", seq_type: "VI"  } });
	instance.vis_nbr = `${seq.seq_prefix}-${Number(seq.seq_curr_val)+1}`;
	await Sequence.update({ seq_curr_val: Number(seq.seq_curr_val )+1 }, { where: { seq_type: "VI", seq_seq: "VI" } });
	});
export default Visite;
