import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const VoucherOrderDetail = sequelize.define(
    "VoucherOrderDetail",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },       
        vdh_inv_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "vh_hist",
                key: "vh_inv_nbr",
            },
        },
        vdh_line: Sequelize.INTEGER,
        vdh_part: {
            type: Sequelize.STRING,
            references:{
                model: "pt_mstr",
                key: "pt_part",
            },

        },

        vdh_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
vdh_due_date: Sequelize.DATEONLY,
vdh_per_date: Sequelize.DATEONLY,
vdh_req_date: Sequelize.DATEONLY,
vdh_qty_ord:  {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_ship: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_inv: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_loc: Sequelize.STRING,
vdh_type: Sequelize.STRING,
vdh_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_acct: Sequelize.STRING,
vdh_abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_serial: Sequelize.STRING,
vdh_desc: Sequelize.STRING,
vdh_um: Sequelize.STRING,
vdh_cc: Sequelize.STRING,
vdh_comment: Sequelize.STRING,
vdh_lot: Sequelize.STRING,
vdh_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_fa_nbr: Sequelize.STRING,
vdh_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_project: Sequelize.STRING,
vdh_cmtindx: Sequelize.INTEGER,
vdh_custpart: Sequelize.STRING,
vdh__qad01: Sequelize.INTEGER,
vdh_status: Sequelize.STRING,
vdh_xslspsn: Sequelize.STRING,
vdh_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_dsc_acct: Sequelize.STRING,
vdh_dsc_cc: Sequelize.STRING,
vdh_list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_user1: Sequelize.STRING,
vdh_user2: Sequelize.STRING,
vdh_sob_rev: Sequelize.DATEONLY,
vdh_sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_expire: Sequelize.DATEONLY,
vdh__qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_taxc: Sequelize.STRING,
vdh_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_site: Sequelize.STRING,
vdh_prodline: Sequelize.STRING,
vdh_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh__chr01: Sequelize.STRING,
vdh__chr02: Sequelize.STRING,
vdh__chr03: Sequelize.STRING,
vdh__chr04: Sequelize.STRING,
vdh__chr05: Sequelize.STRING,
vdh__chr06: Sequelize.STRING,
vdh__chr07: Sequelize.STRING,
vdh__chr08: Sequelize.STRING,
vdh__chr09: Sequelize.STRING,
vdh__chr10: Sequelize.STRING,
vdh__dte01: Sequelize.DATEONLY,
vdh__dte02: Sequelize.DATEONLY,
vdh__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh__log01: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_curr: Sequelize.STRING,
vdh_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_curr_rlse_id: Sequelize.STRING,
vdh_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_contr_id: Sequelize.STRING,
vdh_pickdate: Sequelize.DATEONLY,
vdh_confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_cum_date: Sequelize.DATEONLY,
vdh_for: Sequelize.STRING,
vdh_ref: Sequelize.INTEGER,
vdh_qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_rma_type: Sequelize.STRING,
vdh_owner: Sequelize.STRING,
vdh_calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_slspsn: Sequelize.STRING,
vdh_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_pkg_code: Sequelize.STRING,
vdh_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_fsm_type: Sequelize.STRING,
vdh_conrep: Sequelize.STRING,
vdh_sch_data: Sequelize.STRING,
vdh_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_rlse_nbr: Sequelize.INTEGER,
vdh_start_eff: Sequelize.DATEONLY,
vdh_end_eff: Sequelize.DATEONLY,
vdh_dock: Sequelize.STRING,
vdh_pr_list: Sequelize.STRING,
vdh_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_out_po: Sequelize.STRING,
vdh_raw_days: Sequelize.INTEGER,
vdh_fab_days: Sequelize.INTEGER,
vdh_tax_usage: Sequelize.STRING,
vdh_rbkt_days: Sequelize.INTEGER,
vdh_rbkt_weeks: Sequelize.INTEGER,
vdh_rbkt_mths: Sequelize.INTEGER,
vdh_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_pastdue: Sequelize.STRING,
vdh_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_fr_wt_um: Sequelize.STRING,
vdh_fr_class: Sequelize.STRING,
vdh_fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_ship: Sequelize.STRING,
vdh_sa_nbr: Sequelize.STRING,
vdh_enduser: Sequelize.STRING,
vdh_isb_loc: Sequelize.STRING,
vdh_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_isb_ref: Sequelize.INTEGER,
vdh_auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_drp_ref: Sequelize.STRING,
vdh_tax_env: Sequelize.STRING,
vdh_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_fr_list: Sequelize.STRING,
vdh_pricing_dt: Sequelize.DATEONLY,
vdh_act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_ca_line: Sequelize.INTEGER,
vdh_qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_ca_nbr: Sequelize.STRING,
vdh_qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_to_loc: Sequelize.STRING,
vdh_to_site: Sequelize.STRING,
vdh_to_ref: Sequelize.STRING,
vdh_ln_ref: Sequelize.STRING,
vdh_qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_sad_line: Sequelize.INTEGER,
vdh_warr_start: Sequelize.DATEONLY,
vdh_mod_userid: Sequelize.STRING,
vdh_mod_date: Sequelize.DATEONLY,
vdh_sv_code: Sequelize.STRING,
vdh_alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_for_serial: Sequelize.STRING,
vdh_override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh__qadc01: Sequelize.STRING,
vdh__qadc02: Sequelize.STRING,
vdh__qadc03: Sequelize.STRING,
vdh__qadc04: Sequelize.STRING,
vdh__qadt01: Sequelize.DATEONLY,
vdh__qadt02: Sequelize.DATEONLY,
vdh__qadt03: Sequelize.DATEONLY,
vdh__qadt04: Sequelize.DATEONLY,
vdh__qadd01: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh__qadd02: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh__qadd03: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh__qadl03: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh__qadi01: Sequelize.INTEGER,
vdh__qadi02: Sequelize.INTEGER,
vdh_bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_btb_type: Sequelize.STRING,
vdh_btb_po: Sequelize.STRING,
vdh_btb_pod_line: Sequelize.INTEGER,
vdh_btb_vend: Sequelize.STRING,
vdh_exp_del: Sequelize.DATEONLY,
vdh_dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_cfg_type: Sequelize.STRING,
vdh_div: Sequelize.STRING,
vdh_pl_priority: Sequelize.INTEGER,
vdh_prig1: Sequelize.STRING,
vdh_prig2: Sequelize.STRING,
vdh__qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_sub: Sequelize.STRING,
vdh_dsc_sub: Sequelize.STRING,
vdh_dsc_project: Sequelize.STRING,
vdh_qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdh_cum_time: Sequelize.INTEGER,
vdh_ship_part: Sequelize.STRING,
vdh_promise_date: Sequelize.DATEONLY,
vdh_charge_type: Sequelize.STRING,
vdh_order_category: Sequelize.STRING,
vdh_modelyr: Sequelize.STRING,
vdh_custref: Sequelize.STRING,
vdh_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_max_aging_days: Sequelize.INTEGER,
vdh_consign_loc: Sequelize.STRING,
vdh_intrans_loc: Sequelize.STRING,
vdh_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdh_req_time: Sequelize.STRING,


vdh_domain: {
    type: Sequelize.STRING,
    defaultValue: 'zitouni'
},
oid_vdh_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
...base,
    },
    {
        tableName: "vdh_det",
    }
)
export default VoucherOrderDetail
