import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const WorkRouting = sequelize.define(
    "ro",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        ro_routing: Sequelize.STRING,
	ro_op: {type: Sequelize.DECIMAL, defaultValue : 0 } ,
	ro_desc: Sequelize.STRING,
	ro_wkctr: Sequelize.STRING,
	ro_setup: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_run: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_move: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_yield_pct: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_tool: Sequelize.STRING,
	ro_vend: Sequelize.STRING,
	ro_sub_cost: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_start: Sequelize.DATEONLY,
	ro_end: Sequelize.DATEONLY,
	ro_tran_qty: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_inv_value: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_cmtindx: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_mch: Sequelize.STRING,
	ro_milestone: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_batch: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_user1: Sequelize.STRING,
	ro_user2: Sequelize.STRING,
	ro_std_op: Sequelize.STRING,
	ro_setup_men: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_men_mch: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_mch_op: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_lbr_ovhd: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_queue: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_wait: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_sub_lead: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_cyc_unit: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_cyc_rate: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro__chr01: Sequelize.STRING,
	ro__chr02: Sequelize.STRING,
	ro__chr03: Sequelize.STRING,
	ro__chr04: Sequelize.STRING,
	ro__chr05: Sequelize.STRING,
	ro__dte01: Sequelize.DATEONLY,
	ro__dte02: Sequelize.DATEONLY,
	ro__dec01: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro__dec02: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro__log01: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_std_batch: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_rollup: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_rollup_id: Sequelize.STRING,
	ro_elm_lbr: Sequelize.STRING,
	ro_elm_bdn: Sequelize.STRING,
	ro_elm_sub: Sequelize.STRING,
	ro_start_ecn: Sequelize.STRING,
	ro_end_ecn: Sequelize.STRING,
	ro_po_nbr: Sequelize.STRING,
	ro_po_line: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_mv_nxt_op: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_wipmtl_part: Sequelize.STRING,
	ro_auto_lbr: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_bom_code: Sequelize.STRING,
	ro_cost: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_fsm_type: Sequelize.STRING,
	ro_price: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro_mod_date: Sequelize.DATEONLY,
	ro_mod_userid: Sequelize.STRING,
	ro__qadc01: Sequelize.STRING,
	ro__qadc02: Sequelize.STRING,
	ro__qadc03: Sequelize.STRING,
	ro__qade01: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro__qade02: {type: Sequelize.DECIMAL, defaultValue : 0 },
	ro__qadt01: Sequelize.DATEONLY,
	ro__qadt02: Sequelize.DATEONLY,
	ro__qadl01: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro__qadl02: {type: Sequelize.BOOLEAN, defaultValue : false },
	ro_fsc_code: Sequelize.STRING,
	ro_domain: {type: Sequelize.STRING, defaultValue: 'zitouni' },

     
        oid_ro_det: {type: Sequelize.DECIMAL, defaultValue : 0  },
        ...base,
    },
    {
        tableName: "ro_det",
    }
)
export default WorkRouting
